<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ ?>

<div class="row-fluid">
	<div class="span2">
		<?php echo $this->includeModule('admin/cms:menu'); ?>		
	</div><!--/span-->
	<div class="span10">
		
		<div class="page-header">
			<h1><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></h1>
		</div>		
		
<?php

$options = new Ajde_Crud_Options();
$options
	->selectFields()
		->selectField('name')
			->setEmphasis(true)
			->up()
		->selectField('description')
			->setDisableRichText(true)
			->up()
		->selectField('media')
			//->setType('media')
			//->setThumbDim(266, 100)
			->up()
		->selectField('published')
			->setType('boolean')
			->setHelp('Item is visible or not')
			->up()
		->selectField('sort')
			->setType('sort')
			->up()
		->selectField('url')
			->setIsReadonly(true)
			->setLabel('URL')
			->up()
		->selectField('additional_media')
			->setType('multiple')
			->setEditRoute('media/edit.crud')
			->addTableFileField('filename', 'public/images/uploads/')
			->setModelName('media')
			->addTableField('sort')
			->setShowLabel(false)
			->setCrossReferenceTable('node_media')
			->up()
		->selectField('tag')
			->setType('multiple')
			->setEditRoute('tag/edit.crud')
			->setThumbDim(30, 30)
			->setShowLabel(false)
			->setCrossReferenceTable('node_tag')
			->up()
		->selectField('added')
			->setIsReadonly(true)
			->up()
		->up()
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->setCustom('view', 'View', 'view')
			->up()
		->setMain('name')
		->setShow(array('nodetype', 'name', 'added', 'published', 'sort'))
		->setThumbDim(50, 50)
		->selectView()
			->setOrderBy('sort')
			->up()
		->up()
	->selectEdit()
		->setShow()
		->selectLayout()
			->addRow()
				->addColumn()
					->addBlock()
						->setTitle('Type')
						->setShow(array('nodetype'))
						->up()
					->up()
				->up()
			->addRow()
				->addColumn()
                    ->setSpan(8)
					->addBlock()
						->setShow(array('name', 'subtitle', 'content', 'description'))
						->up()
					->addBlock()
						->setTitle('Additional media')
						->setShow(array('additional_media'))
						->up()
					->up()
				->addColumn()
					->setSpan(4)
					->addBlock()
						->setTitle('Featured image')
						->setClass('sidebar')
						->setShow(array('media'))
						->up()
					->addBlock()
						->setTitle('Tags')
						->setClass('sidebar')
						->setShow(array('tag'))
						->up()
					->addBlock()
						->setTitle('Metadata')
						->setClass('sidebar')
						->setShow(array('added', 'updated', 'published', 'url', 'user', 'sort'))

	->finished();

$crud = $this->ACCrudList('node', $options);

if (Ajde::app()->getRequest()->has('new')) {
	$user = UserModel::getLoggedIn();
	$crud->setOption('fields.user.value', $user->getPK());
}

echo $crud->output();

?>

		
	</div><!--/span-->
</div><!--/row-->