<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$options = new Ajde_Crud_Options();
$options
	->selectFields()
		->selectField('nodetype')
			->setOrderBy('sort')
			->setIsRequired(false)
			->up()
		->selectField('name')
			->setEmphasis(true)
			->up()
		->selectField('description')
			->setDisableRichText(true)
			->up()
		->selectField('media')
			->setIsRequired(true)
			->setShowLabel(false)
			->setUsePopupSelector(true)
			->setListRoute('admin/media:view.crud')
			->setUseImage(true)
			->addTableFileField('thumbnail', 'public/images/uploads/')
			->setThumbDim(300, 300)
			->up()
		->selectField('published')
			->setType('boolean')
			->up()
		->selectField('sort')
			->setType('sort')
			->up()
		->selectField('url')
			->setIsReadonly(true)
			->setLabel('URL')
			->up()
		->selectField('additional_media')
			->setType('multiple')
			->setEditRoute('admin/media:view.crud')
			->addTableFileField('thumbnail', 'public/images/uploads/')
			->setUsePopupSelector(true)
			->setListRoute('admin/media:view.crud')
			->setModelName('media')
			->setThumbDim(100, 30)
			->addSortField('sort')
			->setShowLabel(false)
			->setCrossReferenceTable('node_media')
			->up()
		->selectField('children')
			->setModelName('node')
			->setParent('parent')
			->setHideInIframe(true)
			->setType('multiple')
			->setEditRoute('admin/node:view.crud')
			->addTableField('nodetype')
			->addSortField('sort')
			->setShowLabel(false)
			->up()
		->selectField('parent')
			->setType('fk')
			->setModelName('node')
			->setShowLabel(false)
			->setUsePopupSelector(true)
			->setListRoute('admin/node:view.crud')
			->up()
		->selectField('tag')
			->setType('multiple')
			->setEditRoute('admin/tag:view.crud')
			->setThumbDim(30, 30)
			->setShowLabel(false)
			->setCrossReferenceTable('node_tag')
            ->setSimpleSelector(true)
			->up()
		->selectField('added')
			->setIsReadonly(true)
			->up()
		->up()
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->addItemButton('view', 'view')
			->up()
		->setMain('name')
		->setShow(array('name', 'added', 'published', 'sort'))
		->setThumbDim(50, 50)
		->selectView()
			->setMainFilter('nodetype')
			->setOrderBy('sort')
			->up()
		->up()
	->selectEdit()
		->setShow()
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(8)
					->addBlock()
						->setShow(array('name', 'subtitle', 'content', 'description'))
						->up()
					->addBlock()
                        ->setClass('sidebar well')
						->setTitle('Additional media')
						->setShow(array('additional_media'))
						->up()
					->addBlock()
                        ->setClass('sidebar well')
						->setTitle('Child nodes')
						->setShow(array('children'))
						->up()
					->up()
				->addColumn()
					->setSpan(4)
					->addBlock()
						->setTitle('Featured image')
						->setClass('sidebar well')
						->setShow(array('media'))
						->up()
					->addBlock()
						->setTitle('Tags')
						->setClass('sidebar well')
						->setShow(array('tag'))
						->up()
					->addBlock()
						->setTitle('Parent node')
						->setClass('sidebar well')
						->setShow(array('parent'))
						->up()
					->addBlock()
						->setTitle('Metadata')
						->setClass('sidebar well')
						->setShow(array('added', 'updated', 'published', 'url', 'user', 'sort'))

	->finished();

$crud = $this->ACCrudList('node', $options);

if (Ajde::app()->getRequest()->has('new')) {
	$user = UserModel::getLoggedIn();
	$crud->setOption('fields.user.value', $user->getPK());
}

?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/cms:menu'); ?>		
	</div><!--/span-->
	<div class="span10 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
				<?php echo $this->ACCrudMainFilterBadge($crud); ?>
			</h1>
		</div>		
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->