<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

?>

<div class="row-fluid">
	<div class="span12 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo Ajde::app()->getDocument()->getTitle(); ?>
			</h1>
		</div>		
		
		<div class="row-fluid">
			<div class="span8 offset2">
				
				<h2><?php echo date('d F Y', $this->monday); ?> - <?php echo date('d F Y', strtotime('+7 days', $this->monday)); ?></h2>
				
				<table class="table table-striped table-hover">
					
					<thead>
						<tr>
							<th></th>
							<?php for($i = 0; $i < 7; $i++) {
								if (date('d m Y', strtotime('+' . $i . ' days', $this->monday)) == date('d m Y')) { ?>
									<th><span class='badge badge-inverse'><?php echo date('l', strtotime('+' . $i . ' days', $this->monday)); ?></span></th>
								<?php } else { ?>
									<th><?php echo date('l', strtotime('+' . $i . ' days', $this->monday)); ?></th>
								<?php } ?>
							<?php } ?>
							<th>&sum;</th>
						</tr>
					</thead>
					
					<tbody>
						<?php
						$i = 0;
						foreach($this->table as $row) {
							if ($row['total'] > 0) { ?>
								<tr>
									<td><?php echo _e($row['client']); ?></td>
								<?php foreach($row['columns'] as $day => $column) {
									$i++; ?>
									<td>
										<?php if ($column) { ?>
											<a href='javascript:void(null);' class='work'
											   data-element='#popover-<?php echo $i; ?>'
											   data-trigger='click'
											   data-placement='bottom'
											   data-html='true'
											   >
												€&nbsp;<?php echo $column; ?>
											</a>
											<span class='popover' id='popover-<?php echo $i; ?>'>
												<table class="table">
												<?php foreach ($row['issues'][$day] as $issue) { ?>
													<tr>
														<td>
															<a href="?edit=<?php echo $issue['id']; ?>"><?php echo $issue['title']; ?></a>
														</td>
														<td>€&nbsp;<?php echo $issue['revenue']; ?></td>
													</tr>												
												<?php } ?>
												</table>
											</span>
										<?php } ?>
									</td>
								<?php } ?>
									<td>€&nbsp;<?php echo $row['total']; ?></td>
								</tr>
							<?php }
						} ?>
					</tbody>
					
					<tfoot>
						<tr>
							<th>&sum;</th>
							<?php for($i = 1; $i < 8; $i++) { ?>
								<th><span class='badge'>€&nbsp;<?php echo $this->totals[$i]; ?></span></th>
							<?php } ?>	
							<th>
								<span class='badge'>€&nbsp;<?php echo $this->weektotal; ?></span>
							</th>
						</tr>
					</tfoot>
					
				</table>
				
				<div class="btn-group pull-right">
					<a class="btn" href="report/profit:weekly?week=<?php echo $this->week - 1; ?>">previous</a>
					<a class="btn" href="report/profit:weekly"><i class="icon-screenshot"></i></a>
					<a class="btn" href="report/profit:weekly?week=<?php echo $this->week + 1; ?>">next</a>
				</div>
				
			</div><!--/span-->
		</div>
		
	</div><!--/span-->
</div><!--/row-->