<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireJs('crud/field/timespan', 'html', MODULE_DIR . '_core/');
		
?>

<!-- Timer modal -->
<div
	id="worklog"
	class="modal hide fade"
	tabindex="-1"
	role="dialog"
	aria-labelledby="worklog"
	aria-hidden="true"
>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Worklog description</h3>
	</div>
	<div class="modal-body">
		
		<form class="form-horizontal">
			<div class="control-group">
				<label class="control-label" for="work_description">Description</label>
				<div class="controls">
					<textarea id="work_description" rows="3"></textarea>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="work_span">Time spent</label>
				<div class="controls">
					<input type="hidden" id="work_seconds" value="">
					<input type="text" id="work_span" class="timespan">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label" for="seconds">Issue status</label>
				<div class="controls">
					<fieldset class='picker-container'>
						<input type='radio' id='work_status' name="work_issue_status" class='picker' value="" checked="checked" />
						<label class="radio" for="work_status">
							Do not change
						</label>
						<input type='radio' id='work_status_approval' name="work_issue_status" value="Waiting for approval" class='picker' />
						<label class="radio" for="work_status_approval">
							<span class="badge badge-warning">Waiting for approval</span>
						</label>					
						<input type='radio' id='work_status_closed' name="work_issue_status" value="Closed" class='picker' />
						<label class="radio" for="work_status_closed">
							<span class="badge">Closed</span>
						</label>	
					</fieldset>
				</div>
			</div>
		</form>
		
	</div>
	<div class="modal-footer">
		<button class="btn btn-success save">save</button>
		<button class="btn" data-dismiss="modal" aria-hidden="true">cancel</button>
	</div>
</div>