<?php
/* @var $timer TimerModel */
$timer = $this->timer;

?>

<li class="dropdown timerwidget_container <?php if ($timer) { if ($timer->isPaused()) { echo 'paused'; } else { echo 'active'; } } ?>">
	<a class="dropdown-toggle" data-toggle="dropdown" href="timer">
		<i class="icon-time icon-white"></i>
		<i class="icon-eye-close icon-white"></i>
		<i class="icon-pause icon-white"></i>
		Timer <b class="caret"></b>
	</a>
	<ul class="dropdown-menu timer">
		<div class="timerwidget">
			<div class="active_container">
				<b>Working on</b>
				<span class="issue">
					<a href="issue/view?edit=<?php if ($timer) { echo $timer->getNode()->getPK(); } ?>"><?php if ($timer) { echo _e($timer->getNode()->displayField()); } ?></a>
				</span>
				<b>Duration</b>
				<span class="duration" data-seconds="<?php if ($timer) { echo _e($timer->getElapsed()); } ?>"></span>
				<div class="buttons btn-group">
					<a class="btn pause"><i class="icon-pause"></i></a>
					<a class="btn resume"><i class="icon-play"></i></a>
					<a class="btn btn-success done"><i class="icon-ok icon-white"></i> done</a>
					<a class="btn cancel"><i class="icon-remove"></i></a>
				</div>
			</div>
			<div class="inactive_container">
				<b>No active timer</b>
				<a href="issue">Start working</a>!
			</div>
		</div>
	</ul>
</li>