<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<!--<h1>Status 403</h1>
<p>&nbsp;</p>-->
<h3><?php echo __("We've taken a security measure"); ?></h3>
<p>&nbsp;</p>
<p>
	You may have looked this page up some time, or from another location or device, and it has expired.
</p>
<p>&nbsp;</p>
<p>
	<a class='btn' href='javascript:void(0);' onclick='window.location.reload(true);'>
		<?php echo __("reload this page"); ?>
	</a>
</p>