w<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="container">

<div class="row-fluid">

	<div class="span12 col-12">
		<div class="page-header">
			<h1><?php echo __("We've taken a security measure"); ?></h1>
		</div>
	</div>
	
</div>
	
<div class="row-fluid">
	
	<div class="span8 col-12 col-lg-4">			
		<p>
        	You may have looked this page up some time, or from another location or device, and it has expired.
		</p>
        <a class='action btn btn-primary' href='javascript:void(0);' onclick='window.location.reload(true);'>
        	<?php echo __("Reload this page"); ?>
        </a>
	</div>
	
	<div class="span4 col-12 col-lg-6 col-lg-offset-2 col-offset-2">
		<img src="http://2.bp.blogspot.com/-IqXGVlCP0jo/T2y8koA137I/AAAAAAAADbk/VWU059O1j1w/s1600/404.jpg" class="img-responsive" />
	</div>
	
</div><!--/row-->

</div>