<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<!--<h1>Status 404</h1>
<p>&nbsp;</p>-->
<h3><?php echo __("We're sorry, this page can not be found"); ?></h3>
<p>&nbsp;</p>
<p>
	We tried everything we could to find the page you're looking for,<br/>
	but had to give up in the end.
</p>
<p>&nbsp;</p>
<p>
	<a class='action' href='.'>
		<?php echo __("Take me to the homepage"); ?>
	</a>
</p>