<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="row-fluid">

	<div class="span12 col-12">
		<div class="page-header">
			<h1><?php echo __("We're sorry, something went wrong"); ?></h1>
		</div>
	</div>
	
</div>
	
<div class="row-fluid">
	
	<div class="span8 col-12 col-lg-4">			
		<p>
        	We tried everything we could to render the page you're looking for,<br/>
			but encountered some internal problems.
		</p>
        <a class='action btn btn-success' href='.'>
        	<?php echo __("Take me to the homepage"); ?>
        </a>
	</div>
	
	<div class="span4 col-12 col-lg-6 col-lg-offset-2">
		<img src="http://2.bp.blogspot.com/-IqXGVlCP0jo/T2y8koA137I/AAAAAAAADbk/VWU059O1j1w/s1600/404.jpg" class="img-responsive" />
	</div>
	
</div><!--/row-->