<div class="well sidebar-nav">
	<a class="menu-toggle btn btn-normal pull-right"><i class="icon-resize-small"></i></a>
    <ul class="nav nav-list">
        <li class="nav-header">Shop</li>
        <li><a href="admin/shop:products">Product catalogue</a></li>
        <li class="divider"></li>
        <li><a href="admin/shop:transactions">Transactions</a></li>
        <li><a href="admin/shop:carts">Carts</a></li>
    </ul>
</div><!--/.well -->