<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */

$options = new Ajde_Crud_Options();
$options
	->selectFields()
		->selectField('comment')
			->setEmphasis(true)
			->up()
        ->selectField('secret')
            ->setIsReadonly(true)
            ->up()
        ->selectField('secret_archive')
            ->setDisableRichText(true)
            ->setIsReadonly(true)
            ->up()
        ->selectField('extra')
            ->setDisableRichText(true)
            ->setLength(255)
            ->up()
        ->selectField('comment')
            ->setDisableRichText(true)
            ->setIsReadonly(true)
            ->setEmphasis(true)
            ->setLength(255)
            ->up()
        ->selectField('payment_details')
            ->setDisableRichText(true)
            ->up()
        ->selectField('payment_providerid')
            ->setDisableRichText(true)
            ->setLength(255)
            ->up()
        ->selectField('shipment_trackingcode')
            ->setDisableRichText(true)
            ->setLength(255)
            ->up()
        ->selectField('payment_amount')
            ->setFunction('getFormattedTotal')
            ->up()
        ->selectField('shipment_address')
            ->setDisableRichText(true)
            ->setLength(0)
            ->up()
		->up()
	->selectList()
		->selectButtons()
			->setEdit(true)
            ->setNew(false)
			->up()
		->setMain('comment')
        ->setShow(array('comment', 'name', 'payment_provider', 'payment_amount', 'payment_status', 'shipment_method', 'added'))
		->selectView()
			->setOrderBy('modified')
            ->setOrderDir('DESC')
			->up()
		->up()
	->selectEdit()
        ->setIsReadonly(true)
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(8)
					->addBlock()
						->setShow(array('comment'))
                        ->up()
                    ->addBlock()
                        ->setTitle('User')
                        ->setShow(array('name', 'email', 'user', 'ip'))
                        ->up()
                    ->addBlock()
                        ->setTitle('Payment')
                        ->setShow(array('payment_provider', 'payment_status', 'payment_details', 'payment_providerid', 'payment_amount'))
                        ->up()
                    ->addBlock()
                        ->setTitle('Shipment')
                        ->setShow(array('shipment_address', 'shipment_zipcode', 'shipment_city', 'shipment_region', 'shipment_country', 'shipment_status', 'shipment_itemsqty', 'shipment_itemsvatamount', 'shipment_itemstotal', 'shipment_description', 'shipment_method', 'shipment_cost', 'shipment_trackingcode'))
                        ->up()
                    ->up()
                ->addColumn()
                    ->setSpan(4)
                    ->addBlock()
                        ->setTitle('Metadata')
                        ->setClass('sidebar well')
                        ->setShow(array('extra', 'secret', 'secret_archive', 'modified'))
                        ->up()

	->finished();

$crud = $this->ACCrudList('transaction', $options);

?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/shop:menu'); ?>
	</div><!--/span-->
	<div class="span10 expandInIframe">

		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>

		<?php echo $crud->output(); ?>

	</div><!--/span-->
</div><!--/row-->