<?php

// The user
$user = UserModel::getLoggedIn();

?>

<div class="nav-collapse collapse">
    <?php if ($user) { ?>
        <ul class="nav pull-right">
            <?php if ($user && (string) $user->getUsergroup() == UserModel::USERGROUP_ADMINS) { ?>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="admin/setup:nodes">Setup <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="nav-header">Meta setup</li>
                        <li><a href="admin/setup:nodes">Nodes</a></li>
                        <li><a href="admin/setup:media">Media</a></li>
                        <li><a href="admin/setup:menus">Menus</a></li>
                        <li><a href="admin/setup:settings">Settings</a></li>
                        <li class="divider"></li>
                        <li><a href="admin/setup:meta">Meta fields</a></li>
                        <li class="nav-header">Access</li>
                        <li><a href="admin/user:view">Users</a></li>
                        <li><a href="admin/acl:view">Pages &amp; models</a></li>
                        <li class="nav-header">Maintenance</li>
                        <li><a href="admin/system:cleanuploads">Clean uploads</a></li>
                        <li><a href="admin/system:check">System check</a></li>
                        <li><a href="admin/system:update">Update</a></li>
                        <li><a href="admin/system:log">Log</a></li>
                    </ul>
                </li>
            <?php } ?>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="user">
                    <?php echo Ajde_Resource_Image_Gravatar::get($user->getEmail(), 18, 'identicon', 'g', true); ?> &nbsp;
                    <?php echo $user->getUsername(); ?> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="user">Profile</a></li>
                    <li><a href="user/social">Social</a></li>
                    <li><a href="user/settings">Settings</a></li>
                    <li><a href="user/app">App</a></li>
                    <li class="divider"></li>
                    <li><a href="user/logoff">Log out</a></li>
                </ul>
            </li>
        </ul>
        <form class="navbar-search pull-right">
            <input type="text" name="q" id="node-search" placeholder="Search nodes">
            <div id="node-search-results"></div>
        </form>
    <?php } else { ?>
        <ul class="nav pull-right">
            <li><a href="user/logon">Login</a></li>
        </ul>
    <?php } ?>

    <ul class="nav">
        <?php if ($user) { ?>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="admin/cms:nodes">Content <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <?php
                    $extendedMenu = false;
                    if ($extendedMenu) { ?>
                        <li class="nav-header">Nodes</li>
                        <li><a href="admin/node:view">Overview</a></li>
                        <?php foreach ($nodeTypes as $nodeType) {
                            /* @var $nodeType NodetypeModel */
                            if ($nodeType->get('category') <> $currentGrouper) {
                                if (!empty($currentGrouper)) { echo '</ul>'; }
                                $currentGrouper = $nodeType->get('category'); ?>
                                <li class="with-sub-menu">
                                <a href="javascript:void(null);">
                                    <?php echo ucfirst($currentGrouper); ?> <i class="icon-chevron-right pull-right"></i>
                                </a>
                                <ul class="dropdown-menu sub-menu">
                            <?php } ?>
                            <li><a href="admin/node:view?view[filter][nodetype]=<?php echo $nodeType->getPK(); ?>"><?php echo _e($nodeType->getName()); ?></a></li>
                        <?php }
                        if ($nodeTypes->count() && !empty($currentGrouper)) { ?>
                            </ul>
                            </li>
                        <?php } ?>
                        <li class="divider"></li>
                    <?php } else { ?>
                        <li><a href="admin/node:view">Node overview</a></li>
                    <?php } ?>
                    <li><a href="admin/media:view">Media manager</a></li>
                    <li><a href="admin/menu:view">Menu editor</a></li>
                    <li><a href="admin/tag:view">Tag manager</a></li>
                    <li><a href="admin/email:view">E-mail manager</a></li>
                    <li><a href="admin/form:view">Form manager</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="admin/shop">Shop <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="admin/shop:products">Product catalogue</a></li>
                    <li class="divider"></li>
                    <li><a href="admin/shop:transactions">Transactions</a></li>
                    <li><a href="admin/shop:carts">Carts</a></li>
                </ul>
            </li>
            <?php echo Ajde_Event::trigger('Ajde_Layout', 'onAdminMenu'); ?>
            <li><a href="admin/cms:settings">Settings</a></li>
        <?php } ?>
    </ul>
</div>