<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="row-fluid">
	<div class="span2">
	</div><!--/span-->
	<div class="span8">
		<div class="hero-unit">
			<h1><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></h1>
			<p>Yay, you reached the dashboard!</p>
			<p>
				<a href="admin/node:view?view[filter][nodetype]=&amp;nofilterpopup=1" class="btn btn-primary btn-large">node overview &raquo;</a>
				<a href="admin/node:view?new&amp;view[filter][nodetype]=" class="btn btn-primary btn-large">add node &raquo;</a>
			</p>
		</div>
		<div class="row-fluid">
			<div class="span4">
				<h2>Media</h2>
				<p>Files and embedded media such as video and audio</p>
				<p><a class="btn" href="admin/media:view">media manager &raquo;</a></p>
			</div><!--/span-->
			<div class="span4">
				<h2>Menus</h2>
				<p>Manage what nodes users can access from the menus</p>
				<p><a class="btn" href="admin/menu:view">menu editor &raquo;</a></p>
			</div><!--/span-->
			<div class="span4">
				<h2>Settings</h2>
				<p>Change some options of your site</p>
				<p><a class="btn" href="admin/cms:settings">change settings &raquo;</a></p>
			</div><!--/span-->
		</div><!--/row-->
	</div><!--/span-->
</div><!--/row-->