ALTER TABLE `cart` MODIFY COLUMN `user`  int(10) UNSIGNED NULL DEFAULT NULL COMMENT 'User' AFTER `id`;
ALTER TABLE `cart` MODIFY COLUMN `client`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Client ID' AFTER `user`;
ALTER TABLE `cart` ADD COLUMN `added`  timestamp NULL DEFAULT NULL COMMENT 'Added' AFTER `client`;
ALTER TABLE `cart` ADD COLUMN `updated`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated' AFTER `added`;
ALTER TABLE `cart_item` MODIFY COLUMN `cart`  int(10) UNSIGNED NOT NULL COMMENT 'Cart' AFTER `id`;
ALTER TABLE `cart_item` MODIFY COLUMN `entity`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Entity' AFTER `cart`;
ALTER TABLE `cart_item` MODIFY COLUMN `entity_id`  int(10) UNSIGNED NOT NULL COMMENT 'Entity ID' AFTER `entity`;
ALTER TABLE `cart_item` MODIFY COLUMN `unitprice`  decimal(8,2) NOT NULL COMMENT 'Unit price' AFTER `entity_id`;
ALTER TABLE `cart_item` MODIFY COLUMN `qty`  tinyint(3) UNSIGNED NOT NULL COMMENT 'Quantity' AFTER `unitprice`;
CREATE TABLE `sso` ( `id`  int(10) UNSIGNED NOT NULL AUTO_INCREMENT , `user`  int(10) UNSIGNED NOT NULL COMMENT 'User' , `provider`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Provider' , `username`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Username at provider' , `avatar`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Avatar at provider' , `uid`  text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'User ID' , `data`  text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Data' , PRIMARY KEY (`id`), CONSTRAINT `sso_ibfk_1` FOREIGN KEY (`user`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, INDEX `user` (`user`) USING BTREE  ) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci ROW_FORMAT=Compact ;
ALTER TABLE `transaction` MODIFY COLUMN `user`  int(10) UNSIGNED NULL DEFAULT NULL COMMENT 'User' AFTER `id`;
ALTER TABLE `transaction` MODIFY COLUMN `ip`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'IP address' AFTER `user`;
ALTER TABLE `transaction` MODIFY COLUMN `payment_provider`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Provider' AFTER `ip`;
ALTER TABLE `transaction` MODIFY COLUMN `payment_status`  enum('pending','requested','refused','completed','cancelled') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'pending' COMMENT 'Status' AFTER `payment_provider`;
ALTER TABLE `transaction` MODIFY COLUMN `payment_details`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Details' AFTER `payment_status`;
ALTER TABLE `transaction` ADD COLUMN `payment_providerid`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Provider ID' AFTER `payment_details`;
ALTER TABLE `transaction` MODIFY COLUMN `payment_amount`  decimal(8,2) NOT NULL COMMENT 'Amount' AFTER `payment_providerid`;
ALTER TABLE `transaction` MODIFY COLUMN `name`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Name' AFTER `payment_amount`;
ALTER TABLE `transaction` MODIFY COLUMN `email`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'E-mail' AFTER `name`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_address`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Address' AFTER `email`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_zipcode`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Zipcode' AFTER `shipment_address`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_city`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'City' AFTER `shipment_zipcode`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_region`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Region' AFTER `shipment_city`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_country`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Country' AFTER `shipment_region`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_status`  enum('new','shipped','delivered') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'new' COMMENT 'Status' AFTER `shipment_country`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_itemsqty`  int(11) NOT NULL COMMENT 'Quantity' AFTER `shipment_status`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_itemsvatamount`  decimal(8,2) NOT NULL COMMENT 'VAT' AFTER `shipment_itemsqty`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_itemstotal`  decimal(8,2) NOT NULL COMMENT 'Total' AFTER `shipment_itemsvatamount`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_description`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Description' AFTER `shipment_itemstotal`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_method`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Method' AFTER `shipment_description`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_cost`  decimal(8,2) NOT NULL COMMENT 'Cost' AFTER `shipment_method`;
ALTER TABLE `transaction` MODIFY COLUMN `shipment_trackingcode`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Tracking code' AFTER `shipment_cost`;
ALTER TABLE `transaction` MODIFY COLUMN `comment`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Comment' AFTER `shipment_trackingcode`;
ALTER TABLE `transaction` ADD COLUMN `extra`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Extra information' AFTER `comment`;
ALTER TABLE `transaction` MODIFY COLUMN `secret`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Secret' AFTER `extra`;
ALTER TABLE `transaction` MODIFY COLUMN `secret_archive`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Secret archive' AFTER `secret`;
ALTER TABLE `transaction` MODIFY COLUMN `modified`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modified' AFTER `secret_archive`;
ALTER TABLE `user` ADD COLUMN `avatar`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'Avatar' AFTER `country`;