<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
/* @var $product ProductModel */

$product = $this->product;
?>

<div class="container main">

    <div class="row">
        <div class="col-sm-12">
            <h1><?php echo esc(Ajde::app()->getDocument()->getTitle()); ?></h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <div class="col-sm-6">
                    <?php echo clean($product->content); ?>
                    <p>
                        € <?php echo $product->getFormattedPriceInclVat(); ?>
                        <small>incl. € <?php echo $product->getFormattedVat(); ?> <?php echo trans('VAT'); ?></small>
                    </p>
                    <p>
                        <?php echo $this->includeModule('shop/cart:add/html/product:' . $product->getPK()); ?>
                    </p>
                    <p>
                        <a href="shop"><?php echo trans('Back'); ?></a>
                    </p>
                </div>
                <div class="col-sm-6">
                    <?php if ($image = $product->getImage()) { ?>
                        <figure>
                            <img src="<?php echo esc($image->getUrl(800)); ?>" class="img-responsive" />
                        </figure>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div id='cart'>
                <?php echo $this->includeModule('shop/cart:widget/html/quickcheckout'); ?>
            </div>
        </div>
    </div>

</div>
