<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

/* @var $options Ajde_Crud_Options */
$options = $this->options;

$options
	->selectFields()
		->selectField('issuecount')
			->setLabel('Open issues')
			->setFunction('displayOpenIssueCount')
			->up()
		->up()			
	->selectList()
		->setShow(array('title', 'issuecount', 'sort'))
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->setDelete(false)
			->setSelect(false)
			->addItemButton('new-project', '<i class="icon-plus"></i> project', 'new-project')
			->addItemButton('new-streak', '<i class="icon-plus"></i> streak', 'new-streak')
			->addItemButton('issues', 'issues', 'btn-info nodes', true)
->finished();

$crud = $this->ACCrudList('node', $options);
$crud->setSessionName('project');
$crud->setNewAction('project?view[filter][nodetype]=' . NodeModel::NODETYPE_PROJECT . '&prefill[parent]=' . $this->parent);

$filterGroup = new Ajde_Filter_WhereGroup();
$filters = array(
	NodeModel::NODETYPE_CLIENT,
	NodeModel::NODETYPE_PROJECT,
	NodeModel::NODETYPE_STREAK
);
foreach ($filters as $filter) {
	$filterGroup->addFilter(new Ajde_Filter_Where('nodetype', Ajde_Filter_Where::FILTER_EQUALS, $filter, Ajde_Query::OP_OR));
}
$crud->getCollection()->addFilter($filterGroup);

if (!Ajde::app()->getRequest()->has('edit') && !Ajde::app()->getRequest()->has('new')) {
	// LIST
	$collection = $crud->getCollection();
	/* @var $collection NodeCollection */
	$model = $crud->getModel();
	/* @var $model NodeModel */
	
	// remove mainfilter
	$crudView = $crud->getCollectionView();
	$crudView->setFilter(array());
	
	// add parent filter
	$collection->filterChildrenOfParent($this->parent);
	
	// add node type
	$collection->joinNodetype();
	$collection->getQuery()->addSelect('nodetype.name AS nodetype_name');
	
	// add childrencount
	$crud->getCollection()->getQuery()->addSelect('NULL AS issuecount');
}

if (Ajde::app()->getRequest()->has('new')) {
	// NEW
	
	// set owner
	$user = UserModel::getLoggedIn();
	$crud->setOption('fields.user.value', $user->getPK());
}

?>

<div class="row-fluid">
	<div class="span12 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo Ajde::app()->getDocument()->getTitle(); ?>
				<?php if (Ajde::app()->getRequest()->has('edit') || Ajde::app()->getRequest()->has('new')) {
					echo $this->ACCrudMainFilterBadge($crud, true);
				} ?>
			</h1>
		</div>		
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->