<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireJs('node/panel');
$this->requireJs('node/update');

/* @var $item NodeModel */
$item = $this->item;

?>

<h3>
	<?php echo _e($item->getTitle()); ?>
</h3>

<div class="row-fluid">
	<div class="span4">
		<table class="table table-condensed">
			<tr>
				<td>
					<?php echo $item->getMediaTag(400, 150, true, ''); ?>
				</td>
			</tr>
		</table>
	</div>
	<div class="span4">
		<table class="table table-condensed">
			<tr>
				<td><?php echo _c(Ajde_Component_String::trim( $item->getContent(), 250 )); ?></td>
			</tr>
		</table>
	</div>
	<div class="span4">
		<table class="table table-condensed">
			<tr>
				<th>Published</th>
				<td>					
					<?php echo $item->getPublished() ? 'On' : 'Off'; ?>
				</td>
			</tr>
			<tr>
				<th>Added</th>
				<td>					
					<?php 
					$timestamp = new DateTime($item->get('added'));
					$timestamp = $timestamp->format('U');
					echo Ajde_Component_String::time2str($timestamp);
					?>
				</td>
			</tr>
		</table>
	</div>
</div>