<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$options = NodeController::getNodeOptions();

$crud = $this->ACCrudList('node', $options);

?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/cms:menu'); ?>		
	</div><!--/span-->
	<div class="span10 expandInIframe">
		
		<div class="page-header">
			<h1>
				<!--<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>-->
				<?php echo $this->ACCrudMainFilterBadge($crud, true); ?>
			</h1>
		</div>		
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->