<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ ?>

<h2>
	Tags
</h2>

<?php	

$options = new Ajde_Crud_Options();
$options	
	->selectFields()
		->selectField('name')
			->setEmphasis(true)
			->up()		
		->selectField('sort')
			->setType('sort')
			->up()
		->up()			
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->up()
		->setMain('name')
		->setShow(array('name', 'sort'))		
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
					->addBlock()
						->setShow(array('name'))				
		
	->finished();

$crud = $this->ACCrudList('tag', $options);

echo $crud->output();