<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

?>

<div class="row-fluid">
	<div class="span12 expandInIframe">

		<div class="page-header">
			<h1>
				<?php echo Ajde::app()->getDocument()->getTitle(); ?>
			</h1>
		</div>

		<div class="row-fluid">
			<div class="span8 offset2">

				<h2><?php echo date('d F Y', $this->monday); ?> - <?php echo date('d F Y', strtotime('+7 days', $this->monday)); ?></h2>

				<table class="table table-striped table-hover">

					<thead>
						<tr>
							<th></th>
							<?php for($i = 0; $i < 7; $i++) {
								if (date('d m Y', strtotime('+' . $i . ' days', $this->monday)) == date('d m Y')) { ?>
									<th><span class='badge badge-inverse'><?php echo date('l', strtotime('+' . $i . ' days', $this->monday)); ?></span></th>
								<?php } else { ?>
									<th><?php echo date('l', strtotime('+' . $i . ' days', $this->monday)); ?></th>
								<?php } ?>
							<?php } ?>
						</tr>
					</thead>

					<tbody>
						<?php for($i = 8; $i < 18; $i++) { ?>
							<tr>
								<td class="hour">
									<?php echo str_pad($i, 2, '0', STR_PAD_LEFT); ?>:00
								</td>
								<?php for($j = 1; $j < 8; $j++) {

									// first table of first row
									if ($i == 9 && count($this->table[$j])) {
										echo '<td class="blocks">';
										foreach($this->table[$j] as $block) { ?>
											<a href="?edit=<?php echo $block['id']; ?>" class="block <?php echo str_replace(' ', '_', strtolower($block['status'])); ?> height<?php echo $block['height']; ?> start<?php echo $block['start']; ?>">
												<span class="badge"><?php echo _e($block['client']); ?></span>
												<?php echo _e($block['title']); ?>
											</a>
										<?php }
										echo '</td>';
									} else { ?>
										<td></td>
									<?php } ?>
								<?php } ?>
							</tr>
						<?php } ?>
					</tbody>

					<tfoot>
						<tr>
							<th>&sum;</th>
							<?php for($i = 1; $i < 8; $i++) {
								if (!$this->totals[$i]) { ?>
									<th><span class='badge badge-important'> &nbsp; 0 &nbsp; </span></th>
								<?php } else if ($this->totals[$i] < 8 * 60 * 60) { ?>
									<th><span class='badge badge-warning'><?php echo NodeModel::span2str($this->totals[$i]); ?></span></th>
								<?php } else { ?>
									<th><span class='badge badge-success'><?php echo NodeModel::span2str($this->totals[$i]); ?></span></th>
								<?php } ?>
							<?php } ?>
						</tr>
					</tfoot>

				</table>

				<div class="btn-group pull-right">
					<a class="btn" href="report/hours:planning?week=<?php echo $this->week - 1; ?>">previous</a>
					<a class="btn" href="report/hours:planning"><i class="icon-screenshot"></i></a>
					<a class="btn" href="report/hours:planning?week=<?php echo $this->week + 1; ?>">next</a>
				</div>

			</div><!--/span-->
		</div>

	</div><!--/span-->
</div><!--/row-->