<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

?>

<div class="row-fluid">
	<div class="span12 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo Ajde::app()->getDocument()->getTitle(); ?>
			</h1>
		</div>		
		
		<div class="row-fluid">
			<div class="span8 offset2">
				
				<h2><?php echo date('d F Y', $this->monday); ?> - <?php echo date('d F Y', strtotime('+7 days', $this->monday)); ?></h2>
				
				<table class="table table-striped table-hover">
					
					<thead>
						<tr>
							<th></th>
							<?php for($i = 0; $i < 7; $i++) {
								if (date('d m Y', strtotime('+' . $i . ' days', $this->monday)) == date('d m Y')) { ?>
									<th><span class='badge badge-inverse'><?php echo date('l', strtotime('+' . $i . ' days', $this->monday)); ?></span></th>
								<?php } else { ?>
									<th><?php echo date('l', strtotime('+' . $i . ' days', $this->monday)); ?></th>
								<?php } ?>
							<?php } ?>
							<th>&sum;</th>
						</tr>
					</thead>
					
					<tbody>
						<?php
						$i = 0;
						foreach($this->table as $row) {
							if ($row['total'] > 0) { ?>
								<tr>
									<td><?php echo _e($row['client']); ?></td>
								<?php foreach($row['columns'] as $day => $column) {
									$i++; ?>
									<td>
										<a href='javascript:void(null);' class='work'
										   data-element='#popover-<?php echo $i; ?>'
										   data-trigger='click'
										   data-placement='bottom'
										   data-html='true'
										   ><?php echo NodeModel::span2str($column); ?></a>
										<span class='popover' id='popover-<?php echo $i; ?>'>
											<table class="table">
											<?php foreach ($row['issues'][$day] as $issue) { ?>
												<tr>
													<td>
														<a href="?edit=<?php echo $issue['id']; ?>"><?php echo $issue['title']; ?></a>
													</td>
													<td><?php echo NodeModel::span2str($issue['seconds']); ?></td>
												</tr>												
											<?php } ?>
											</table>
										</span>
									</td>
								<?php } ?>
									<td><?php echo NodeModel::span2str($row['total']); ?></td>
								</tr>
							<?php }
						} ?>
					</tbody>
					
					<tfoot>
						<tr>
							<th>&sum;</th>
							<?php for($i = 1; $i < 8; $i++) {
								if (!$this->totals[$i]) { ?>
									<th><span class='badge badge-important'> &nbsp; 0 &nbsp; </span></th>
								<?php } else if ($this->totals[$i] < 8 * 60 * 60) { ?>
									<th><span class='badge badge-warning'><?php echo NodeModel::span2str($this->totals[$i]); ?></span></th>
								<?php } else { ?>
									<th><span class='badge badge-success'><?php echo NodeModel::span2str($this->totals[$i]); ?></span></th>
								<?php } ?>
							<?php } ?>	
							<th>
								<?php if ($this->weektotal === 0) { ?>
									<span class='badge badge-important'> &nbsp; 0 &nbsp; </span>
								<?php } else if ($this->weektotal < 30 * 60 * 60) { ?>
									<span class='badge badge-important'><?php echo NodeModel::span2str($this->weektotal); ?></span>
								<?php } else if ($this->weektotal < 40 * 60 * 60) { ?>
									<span class='badge badge-warning'><?php echo NodeModel::span2str($this->weektotal); ?></span>
								<?php } else { ?>
									<span class='badge badge-success'><?php echo NodeModel::span2str($this->weektotal); ?></span>
								<?php } ?>
							</th>
						</tr>
					</tfoot>
					
				</table>
				
				<div class="btn-group pull-right">
					<a class="btn" href="report/hours:worked?week=<?php echo $this->week - 1; ?>">previous</a>
					<a class="btn" href="report/hours:worked"><i class="icon-screenshot"></i></a>
					<a class="btn" href="report/hours:worked?week=<?php echo $this->week + 1; ?>">next</a>
				</div>
				
			</div><!--/span-->
		</div>
		
	</div><!--/span-->
</div><!--/row-->