<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

/* @var $transaction Ajde_Shop_Transaction */
$transaction = $this->transaction;
?>

<div class="container main">

    <div class="page-header">
        <h2><?php echo __('Order'); ?></h2>
    </div>

    <?php if ($transaction->hasLoaded() === false) { ?>

        <h4><?php echo __('Order not found'); ?></h4>
        <p><a href='shop'><?php echo __('Back to shop'); ?></a></p>

    <?php } else { ?>

        <div class="row">
            <div class="col-md-6">

                <table class="table table-condensed order">
                    <thead>
                        <tr>
                            <th></th>
                            <th>
                                <h4><?php echo __('Details'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo __('Full name', 'shop') ?></td>
                            <td><?php echo _e($transaction->name); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('E-mail address', 'shop') ?></td>
                            <td><?php echo _e($transaction->email); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Address', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_address); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Zipcode', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_zipcode); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('City', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_city); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Region', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_region); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Country', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_country); ?></td>
                        </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                    <tr>
                        <th>
                            <h4><?php echo __('Comment'); ?></h4>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="left">
                            <?php echo _e($transaction->comment); ?>
                        </td>
                    </tr>
                    </tbody>
                </table>

            </div>
            <div class="col-md-6">

                <table class="table table-condensed order">
                    <thead>
                    <tr>
                        <th>
                            <h4><?php echo __('Order'); ?></h4>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class='summary'>
                            <?php echo _c($transaction->shipment_description); ?>
                        </td>
                    </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                        <tr>
                            <th>
                                <h4><?php echo __('Shipment method'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="left">
                                <?php echo _c($transaction->getShipping()->getCurrentMethod()->getDescription()); ?>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                        <tr>
                            <th>
                                <h4><?php echo __('Status'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="left">
                                <?php switch($transaction->payment_status) {
                                    case 'pending':
                                        echo __('Not paid');
                                        break;
                                    case 'requested':
//                                        echo __('Payment in progress');
                                        ?>

                                        <p>
                                            <?php echo __('Payment was already initiated for this order. If you canceled your payment, you can now reset the payment status of this transaction and try again.') ?>
                                        </p>
                                        <p>
                                            <a href="shop/transaction:resetPayment" class="btn btn-info">
                                                <span class="glyphicon glyphicon-repeat"></span>
                                                <?php echo __('Try again'); ?>
                                            </a>
                                        </p>

                                        <?php
                                        break;
                                    case 'refused':
                                        echo __('Payment refused');
                                        break;
                                    case 'cancelled':
                                        echo __('Cancelled');
                                        break;
                                    case 'completed': ?>

                                        <p>
                                            <img src='<?php echo _e($transaction->getProvider()->getLogo()); ?>' width='75' style='vertical-align: middle;' class="pull-right" />
                                            <?php echo __('Paid'); ?> <?php echo __('with'); ?>
                                            <?php echo $transaction->getProvider()->getName(); ?>
                                        </p>

                                        <?php break;
                                } ?>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

        <?php if ($this->source == 'session' && $transaction->payment_status == 'pending') { ?>
            <div class='toolbar'>
                <a href='shop/transaction:setup' class='btn btn-success btn-lg pull-right'>
                    <?php echo __('Continue with order'); ?>
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
                <a href='shop/transaction:cancel' class="btn btn-danger"><?php echo __('Cancel order'); ?></a>
                <?php echo __('or'); ?>
                <a href='shop'><?php echo __('continue shopping'); ?></a>
            </div>
        <?php } elseif ($this->source == 'session' && $transaction->payment_status == 'refused') { ?>
            <div class='toolbar'>
                <a href='shop/transaction:resetPayment' class='btn btn-success btn-lg pull-right'>
                    <?php echo __('Reset payment and try again'); ?>
                </a>
                <a href='shop/transaction:cancel' class="btn btn-danger"><?php echo __('Cancel order'); ?></a>
            </div>
        <?php } ?>

    <?php } ?>

</div>