<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$options = new Ajde_Crud_Options();
$options	
	->selectFields()
		->selectField('title')
			->setEmphasis(true)
			->up()
		->selectField('file')
			->setType('file')
			->setSaveDir('public/media/upload/')
			->setExtensions(array('png', 'jpg', 'pdf', 'docx'))
			->setMultiple(false)
			->setLabel('Plaatje')
			->setThumbDim(266, 100)
			->up()
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
					->addBlock()
						->setShow(array('title', 'file'))
						->up()
					->up()
				->addColumn()
					->setWidth(300)
					->setAlign('right')
					->addBlock()
						->setTitle('Belongs to')
						->setClass('sidebar')
						->setShow(array('sample'))
						->up()
		
	->finished();

$crud = $this->ACCrudList('download', $options);

if ($crud->isNew()) {
	echo '<h2>New download</h2>';
} else {
	echo '<h2>Edit download</h2>';
}

echo $crud->output();