<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireCss('view.mobile', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="only screen and (max-width: 767px)"');
?>

<div class="eightcol">
	
	<h2>Items</h2>
	<p>
		<a class='action' href='sample/edit.html'>Edit items</a>
	</p>
	<hr/>

	<?php foreach($this->samples as $entry) {
		/* @var $entry Ajde_Model */ ?>
		<h3><?php echo $this->escape( $entry->title ); ?></h3>
		<?php if ($entry->hasNotEmpty('image')) { ?>
		<?php echo $this->ACImage(array(
			'filename' => 'public/media/upload/' . $entry->getImage(),
			'width' => 200,
			'height' => 200,
			'crop' => true,
			'class' => 'right'
		)); ?>
		<?php } ?>		
		<p>
			<?php echo _c( $entry->content ); ?>
		</p>
		<p>
			€ <?php echo money_format('%!i', $entry->getUnitprice() * (1+$entry->getVATPercentage())); ?>
		</p>
		<p>
			<?php echo $this->includeModule('shop/cart:add/html/sample:' . $entry); ?>
		</p>
		<p>
			<em>Updated: <?php echo $this->escape( $entry->updated ); ?></em>
		</p>		
		<div class='clearfix'></div>
		<hr/>
	<?php } ?>

</div>

<aside class="fourcol last">
	<h2>My cart</h2>
	<div id='widget'>
		<?php echo $this->includeModule('shop/cart:widget/html/quickcheckout'); ?>
	</div>
</aside>