<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$options = new Ajde_Crud_Options();
$options
	->selectFields()
		->selectField('name')
			->setEmphasis(true)
			->up()
		->selectField('type')
			->up()
		->selectField('sort')
			->setType('sort')
			->up()
		->selectField('submenus')
			->addShowOnlyWhen('type', 'submenu')
			->setModelName('menu')
			->setParent('parent')
			->setType('multiple')
			->setEditRoute('admin/menu:view.crud')
			->addTableField('type')
			->addSortField('sort')
			->up()	
		->selectField('node')
			->setIsRequired(true)
			->addShowOnlyWhen('type', array('submenu', 'nodelink'))
			->setLabel('Node link')
			->up()
		->selectField('url')
			->setIsRequired(true)
			->addShowOnlyWhen('type', 'url')
			->setDisableRichText(true)
			->setTextInputHeight(1)
			->setLabel('URL')
			->up()
		->selectField('lang')
			->setFunction('displayLang')
			->setType('i18n')
			->setCloneFields(array(
					
			))
			->up()
		->up()
	->selectList()
		->selectButtons()
			->setNew(false)
			->setEdit(true)
			->setDelete(false)
			->setSelect(false)
			->up()
		->setShowHeader(true)
		->setShowFooter(false)
		->setSingleClickEdits(true)
		->setMain('name')
		->setSearch(false)
		->setShow(array('name', 'lang'))
		->selectView()
			->setOrderBy('sort')
			->up()
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(9)
					->addBlock()
						->setClass('primary narrow sidebar')
						->setShow(array('name'))
						->up()
					->addBlock()
						->setClass('sidebar')
						->setShow(array('type'))
						->up()
					->addBlock()
						->setClass('sidebar well')
						->setShow(array('submenus'))
						->up()
					->addBlock()
						->setClass('sidebar well')
						->setShow(array('node'))
						->up()
					->addBlock()
						->setClass('sidebar well')
						->setShow(array('url'))
						->up()
					->up()
				->addColumn()
					->setSpan(3)
					->addBlock()
					->setClass('narrow sidebar well')
					->setShow(array('lang'))
					->up()
						
	->finished();

$crud = $this->ACCrudList('menu', $options);

$collection = $crud->getCollection();
$collection->addFilter(new Ajde_Filter_Where('parent', Ajde_Filter::FILTER_IS, null));

?>

<div class="row-fluid">
	<div class="span3 hideInIframe">
		<?php echo $this->includeModule('admin/cms:menu'); ?>		
	</div><!--/span-->
	<div class="span9 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>		
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->