<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */ 
?>

<div class="row-fluid">
    <div class="span2">
        <?php echo $this->includeModule('admin/acl:menu'); ?>
    </div><!--/span-->
    <div class="span10">
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>			

        <div class="row-fluid">
            <div class="span12">

                <?php echo $this->ACAjaxForm('admin/acl:model.json', 'AclModel', 'form-horizontal'); ?>
                    <input type="hidden" name="model" value="<?php echo $this->model; ?>" />
                    <input type="hidden" name="preset" value="<?php echo $this->preset; ?>" />
                    <fieldset>
                        <div class="controls">
                            <legend><?php echo $this->model . ': ' . $this->preset; ?></legend>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="usergroup-public">
                                public
                            </label>
                            <div class="controls">
                                <input type="hidden" name="usergroup[public][allow]" class="toggle" value="<?php echo implode('|', AclModel::getModelActionsAsArray('public', $this->options['model'], $this->options['extra'], 'allow')); ?>" />
                                <span class="badge badge-inverse">all records</span><br/>
                                <div class="pull-left" data-toggle="buttons-radio">
                                    <button type="button" data-value="deny" class="toggle btn">inherit all operations</button>
                                    <button type="button" data-value="all" class="toggle btn btn-success">allow all operations</button>
                                </div>
                                <div class="btn-group" data-toggle="buttons-checkbox">
                                    <button type="button" data-value="read" class="toggle btn btn-primary">read</button>
                                    <button type="button" data-value="update" class="toggle btn btn-primary">update</button>
                                    <button type="button" data-value="insert" class="toggle btn btn-primary">insert</button>
                                    <button type="button" data-value="delete" class="toggle btn btn-primary">delete</button>
                                </div>
                            </div>
                        </div>
                        <?php foreach($this->usergroups as $usergroup) {
                            /* @var $usergroup UsergroupModel */ ?>
                            <div class="control-group">
                                <label class="control-label" for="usergroup-<?php echo $usergroup->getPK(); ?>"><?php echo $usergroup->name; ?></label>
                                <div class="controls">
                                    <input type="hidden" name="usergroup[<?php echo $usergroup->getPK(); ?>][allow]" class="toggle" value="<?php echo implode('|', AclModel::getModelActionsAsArray($usergroup->getPK(), $this->options['model'], $this->options['extra'], 'allow')); ?>" />
                                    <span class="badge badge-inverse">all records</span><br/>
                                    <div class="pull-left" data-toggle="buttons-radio">
                                        <button type="button" data-value="deny" class="toggle btn">inherit all operations</button>
                                        <button type="button" data-value="all" class="toggle btn btn-success">allow all operations</button>
                                    </div>
                                    <div class="btn-group" data-toggle="buttons-checkbox">
                                        <button type="button" data-value="read" class="toggle btn btn-primary">read</button>
                                        <button type="button" data-value="update" class="toggle btn btn-primary">update</button>
                                        <button type="button" data-value="insert" class="toggle btn btn-primary">insert</button>
                                        <button type="button" data-value="delete" class="toggle btn btn-primary">delete</button>
                                    </div>
                                </div>
                                <div class="controls">
                                    <input type="hidden" name="usergroup[<?php echo $usergroup->getPK(); ?>][parent]" class="toggle" value="<?php echo implode('|', AclModel::getModelActionsAsArray($usergroup->getPK(), $this->options['model'], $this->options['extra'], 'parent')); ?>" />
                                    <span class="badge badge-inverse">client records</span><br/>
                                    <div class="pull-left" data-toggle="buttons-radio">
                                        <button type="button" data-value="deny" class="toggle btn">inherit all operations</button>
                                        <button type="button" data-value="all" class="toggle btn btn-success">allow all operations</button>
                                    </div>
                                    <div class="btn-group" data-toggle="buttons-checkbox">
                                        <button type="button" data-value="read" class="toggle btn btn-primary">read</button>
                                        <button type="button" data-value="update" class="toggle btn btn-primary">update</button>
                                        <button type="button" data-value="insert" class="toggle btn btn-primary">insert</button>
                                        <button type="button" data-value="delete" class="toggle btn btn-primary">delete</button>
                                    </div>
                                </div>
                                <div class="controls">
                                    <input type="hidden" name="usergroup[<?php echo $usergroup->getPK(); ?>][own]" class="toggle" value="<?php echo implode('|', AclModel::getModelActionsAsArray($usergroup->getPK(), $this->options['model'], $this->options['extra'], 'own')); ?>" />
                                    <span class="badge badge-inverse">own records</span><br/>
                                    <div class="pull-left" data-toggle="buttons-radio">
                                        <button type="button" data-value="deny" class="toggle btn">inherit all operations</button>
                                        <button type="button" data-value="all" class="toggle btn btn-success">allow all operations</button>
                                    </div>
                                    <div class="btn-group" data-toggle="buttons-checkbox">
                                        <button type="button" data-value="read" class="toggle btn btn-primary">read</button>
                                        <button type="button" data-value="update" class="toggle btn btn-primary">update</button>
                                        <button type="button" data-value="insert" class="toggle btn btn-primary">insert</button>
                                        <button type="button" data-value="delete" class="toggle btn btn-primary">delete</button>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="form-actions fixed">
                            <div class="btn-group">
                                <button type="submit" class="btn btn-primary">save changes</button>
                                <a href="admin/acl:view" class="btn">cancel</a>
                            </div>
                        </div>
                    </fieldset>
                </form>

            </div><!--/span-->
        </div><!--/row-->
    </div>
</div>
