<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$options = new Ajde_Crud_Options();
$options
	->selectFields()
		->selectField('gravatar')
			->setFunction('displayAvatar')
			->setFunctionArgs(array(40))
			->up()
		->selectField('username')
			->setEmphasis(true)
			->up()
		->selectField('password')
			->setDisableRichText(true)
			->setLength(255)
			->setIsRequired(false)
			->up()
		->selectField('email')
			->setFunction('emailLink')
			->up()
		->selectField('nodes')
			->setLabel('Node access')
			->setType('multiple')
			->setEditRoute('admin/node:view.crud')
			->setListRoute('admin/node:view.crud')
// 			->setAdvancedFilter(array($clientFilter))
			->setSimpleSelector(true)
			->setModelName('node')
			->setCrossReferenceTable('user_node')
			->up()
		->selectField('debug')
			->setType('boolean')
			->up()
        ->selectField('address')
            ->setLength(0)
            ->setDisableRichText(true)
            ->up()
        ->selectField('avatar')
            ->setType('file')
            ->setSaveDir(UPLOAD_DIR . 'avatar' . DIRECTORY_SEPARATOR)
            ->setExtensions(array('jpg', 'jpeg', 'png', 'gif'))
            ->setThumbDim(500, 200)
            ->setMultiple(false)
            ->up()
		->up()
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->addItemButton('login', 'login')
			->addItemButton('reset', 'reset')
			->up()
		->setMain('username')
		->setShow(array('gravatar', 'username', 'usergroup', 'email', 'fullname'))
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(8)
					->addBlock()
// 						->setClass('primary')
						->setShow(array('username', 'password', 'email', 'fullname'))
						->up()
					->addBlock()
						->setTitle('Address')
						->setShow(array('address', 'zipcode', 'city', 'region', 'country'))
						->up()
					->up()
				->addColumn()
					->setSpan(4)
                    ->addBlock()
                        ->setClass('sidebar')
                        ->setShow(array('avatar'))
                        ->up()
					->addBlock()
						->setTitle('Security')
						->setClass('well')
						->setShow(array('usergroup', 'nodes', 'debug'))

	->finished();

$crud = $this->ACCrudList('user', $options);

if (Ajde::app()->getRequest()->has('new')) {
	$crud->setOption('fields.password.isRequired', true);
}

?>

<div class="row-fluid">
	<div class="span12">
		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>		
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->