<?php 

// Node types
Ajde_Model::register('admin');

$nodeTypes = new NodetypeCollection();
$nodeTypes->orderBy('category');
$nodeTypes->orderBy('sort');

$currentGrouper = '';

?>

<div class="btn-group">
	<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
		type <span class="caret"></span>
	</a>
	<ul class="dropdown-menu pull-right type">
		<?php foreach ($nodeTypes as $nodeType) {  
			/* @var $nodeType NodetypeModel */
			if ($nodeType->get('category') <> $currentGrouper) {
				if (!empty($currentGrouper)) { echo '</ul>'; }
				$currentGrouper = $nodeType->get('category'); ?>
				<li class="with-sub-menu">
					<a href="javascript:void(null);">
						<?php echo ucfirst($currentGrouper); ?> <i class="icon-chevron-right pull-right"></i>
					</a>
					<ul class="dropdown-menu sub-menu">
			<?php } ?>
			<li><a href="javascript:void(null);" data-id="<?php echo $nodeType->getPK(); ?>"><?php echo _e($nodeType->getName()); ?></a></li>
		<?php }
		if ($nodeTypes->count() && !empty($currentGrouper)) { ?>
			</ul>
		</li>
		<?php } ?>
	</ul>
</div>