<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ ?>

<div class="row-fluid">
	<div class="span2">
		<?php echo $this->includeModule('admin/cms:menu'); ?>		
	</div><!--/span-->
	<div class="span10">
		
		<div class="page-header">
			<h1><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></h1>
		</div>		
		
<?php

$options = new Ajde_Crud_Options();
$options	
	->selectFields()
		->selectField('name')
			->setEmphasis(true)
			->up()
		->selectField('type')
            ->setIsReadonly(true)
			->up()
        ->selectField('thumbnail')
            ->setIsReadonly(true)
			->up()
		->selectField('pointer')
			->setType('media')
			->setSaveDir('public/images/uploads/')
			->setExtensions(array('png', 'jpg'))
			->setMultiple(false)
			->setThumbDim(266, 100)
            ->setTypeField('type')
            ->setThumbField('thumbnail')
			->up()
		->selectField('sort')
			->setType('sort')
			->up()
        ->selectField('added')
			->setIsReadonly(true)
			->up()
		->up()			
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->up()
		->setMain('name')
		->setShow(array('name', 'type', 'sort'))
		->setThumbDim(50, 50)
		->selectView()
			->setOrderBy('sort')
			->up()
		->up()
	->selectEdit()
		->setShow()
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(8)
					->addBlock()
						->setShow(array('name'))
						->up()
					->addBlock()
						->setTitle('Content')
						->setShow(array('pointer'))
						->up()					
					->up()
				->addColumn()
					->setSpan(4)
                    ->addBlock()
						->setTitle('Metadata')
						->setClass('sidebar well')
						->setShow(array('added', 'updated', 'user', 'sort'))
						->up()	
                    ->addBlock()
                        ->setTitle('Media info')
                        ->setClass('sidebar well')
						->setShow(array('type', 'thumbnail'))
						->up()					
									
		
	->finished();

$crud = $this->ACCrudList('media', $options);

if (Ajde::app()->getRequest()->has('new')) {
	$user = UserModel::getLoggedIn();
	$crud->setOption('fields.user.value', $user->getPK());
}

echo $crud->output();

?>

		
	</div><!--/span-->
</div><!--/row-->