<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

/* @var $transaction Ajde_Shop_Transaction */
$transaction = $this->transaction;
?>

<div class="container main">

    <h2>Payment</h2>

    <?php if ($transaction->hasLoaded() === false) { ?>

        <h4>Order not found</h4>
        <p><a href='shop'>Back to shop</a></p>

    <?php } else { ?>

        <?php echo $this->ACAjaxForm('shop/transaction:payment', null, 'transactionPayment'); ?>

            <h4>Choose method</h4>
            <dl class='form wide'>
                <dt>Total payable amount</dt>
                <dd><?php echo $transaction->getFormattedTotal(); ?></dd>

                <dt>&nbsp;</dt>
                <dd><hr/></dd>

                <dt>&nbsp;</dt>
                <dd class="status"><?php echo trans('Please choose your method of payment') ?></dd>

                <dt>Payment provider:</dt>
                <dd class='provider'>
                    <?php foreach($transaction->getProviders() as $key => $provider) {
                        /* @var $provider Ajde_Shop_Transaction_Provider */ ?>
                    <input type='radio' name='provider' value='<?php echo esc($key); ?>' id='<?php echo esc($key); ?>' /><label for='<?php echo esc($key); ?>'>
                        <?php if ($provider->getLogo()) { ?>
                            <img src='<?php echo esc($provider->getLogo()); ?>' alt='<?php echo esc($provider->getName()); ?>' width='75' style='vertical-align: middle;' />
                        <?php } else { ?>
                            <?php echo esc($provider->getName()); ?>
                        <?php } ?>
                    </label>
                    <?php } ?>
                </dd>
            </dl>

            <div class='toolbar'>
                <input type='submit' class='action' value='Pay &amp; complete order' />
                <a href='shop/transaction:setup'>Edit shipping details</a>
            </div>

        </form>

        <div id="postproxy"></div>

    <?php } ?>

</div>
