<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

/* @var $transaction Ajde_Shop_Transaction */
$transaction = $this->transaction;
?>

<div class="container main">

    <div class="page-header">
        <h2><?php echo trans('Payment') ?></h2>
    </div>

    <div class="row form-group">
        <div class="col-xs-12">
            <ul class="nav nav-pills nav-justified thumbnail setup-panel">
                <li>
                    <a href="shop/checkout">
                        <h4 class="list-group-item-heading">1. <?php echo trans('Review', 'shop'); ?></h4>
                        <p class="list-group-item-text"><?php echo trans('Review your shopping cart', 'shop'); ?></p>
                    </a>
                </li>
                <li>
                    <a href="shop/transaction:setup">
                        <h4 class="list-group-item-heading">2. <?php echo trans('Your details', 'shop'); ?></h4>
                        <p class="list-group-item-text"><?php echo trans('Your name, address and shipping'); ?></p>
                    </a>
                </li>
                <li class="active">
                    <a>
                        <h4 class="list-group-item-heading">3. <?php echo trans('Payment', 'shop'); ?></h4>
                        <p class="list-group-item-text"><?php echo trans('Payment and order confirmation'); ?></p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <?php if ($transaction->hasLoaded() === false) { ?>

        <h4><?php echo trans('Order not found') ?></h4>
        <p><a href='shop'><?php echo trans('Back to shop') ?></a></p>

    <?php } else { ?>

        <?php echo $this->ACAjaxForm('shop/transaction:payment', null, 'transactionPayment form-horizontal'); ?>

            <div class="status">
                <?php echo trans('Please choose your method of payment') ?>
            </div>

            <div class="col-sm-8 col-sm-offset-2">

                <h4><?php echo trans('Order summary'); ?></h4>
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th><?php echo trans('Description'); ?></th>
                            <th class="text-right"><?php echo trans('Amount'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo Ajde_Component_String::makePlural($transaction->shipment_itemsqty, 'item'); ?></td>
                            <td class="text-right"><?php echo $transaction->getFormattedItemsTotal(); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo trans('Shipping with'); ?> <?php echo $transaction->getShipping()->getCurrentMethod()->getDescription(); ?></td>
                            <td class="text-right"><?php echo $transaction->getFormattedShippingTotal(); ?></td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th><?php echo trans('Total payable amount', 'shop') ?></th>
                            <th class="text-right"><?php echo $transaction->getFormattedTotal(); ?></th>
                        </tr>
                    </tfoot>
                </table>

            <hr/>

            </div>

            <?php if ($transaction->payment_status == 'completed') { ?>

                <div class="col-sm-7 col-sm-offset-5">
                    <p><?php echo trans('This transaction is already paid for.') ?></p>
                </div>

            <?php } elseif ($transaction->payment_status != 'pending') { ?>

                <div class="col-sm-7 col-sm-offset-5">
                    <p>
                        <?php echo trans('Payment was already initiated for this order. If you canceled your payment, you can now reset the payment status of this transaction and try again.') ?>
                    </p>
                    <p>
                        <a href="shop/transaction:resetPayment" class="btn btn-info">
                            <span class="glyphicon glyphicon-repeat"></span>
                            <?php echo trans('Try again'); ?>
                        </a>
                        <?php echo trans('or'); ?> <a href="shop/transaction:view"><?php echo trans('View current order'); ?></a>
                    </p>
                </div>

            <?php } else { ?>

                <div class="form-group">
                    <label class="col-sm-5 control-label"><?php echo trans('Choose payment method', 'shop') ?></label>
                    <div class="col-sm-7 provider">

                        <?php foreach($transaction->getProviders() as $key => $provider) {
                            /* @var $provider Ajde_Shop_Transaction_Provider */ ?>
                            <label for='<?php echo esc($key); ?>' data-toggle="tooltip" data-placement="right" title="<?php echo esc($provider->getName()); ?>">
                                <input type='radio' name='provider' value='<?php echo esc($key); ?>' id='<?php echo esc($key); ?>' />
                                <?php if ($provider->getLogo()) { ?>
                                    <img src='<?php echo esc($provider->getLogo()); ?>' alt='<?php echo esc($provider->getName()); ?>' width='75' style='vertical-align: middle;' />
                                <?php } else { ?>
                                    <?php echo esc($provider->getName()); ?>
                                <?php } ?>
                            </label>
                            <br/>
                        <?php } ?>

                    </div>
                </div>

                <div class="clearfix"></div>

                <div class='toolbar'>
                    <button type='submit' class='pull-right btn btn-success btn-lg'>
                        <?php echo esc(trans('Pay and complete order', 'shop')); ?>
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </button>
                    <a href='shop/transaction:setup'>
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <?php echo trans('Edit shipping details', 'shop'); ?>
                    </a>
                </div>

            <?php } ?>

        </form>

        <div id="postproxy"></div>

    <?php } ?>

</div>
