<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="container main">

    <h2><?php echo __('Order refused'); ?></h2>

    <p>
        <?php echo __('The payment for your order has not been received. Please contact us for more information.'); ?>
    </p>
    <p>
        <a href="shop/transaction:resetPayment" class="btn btn-info btn-lg">
            <span class="glyphicon glyphicon-repeat"></span>
            <?php echo __('Try again'); ?>
        </a>
    </p>

</div>