<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="col-sm-7 col-sm-offset-5">
    <h4><?php echo trans('Shipment', 'shop'); ?></h4>
</div>

<?php if ($this->transaction === false || ($this->transaction !== false && empty($this->transaction->shipment_country))) { ?>

    <div class="form-group">
        <label for="comment" class="col-sm-5 control-label"><?php echo trans('Choose shipment method', 'shop') ?></label>
        <div class="col-sm-7 method">
	        <p><?php echo trans('Shipment options will be available after you choose a country...', 'shop') ?></p>
        </div>
    </div>

<?php } else { ?>

    <div class="form-group">
        <label for="comment" class="col-sm-5 control-label"><?php echo trans('Choose shipment method', 'shop') ?></label>
        <div class="col-sm-7 method">

            <table>
                <colgroup>
                    <col width="40" />
                    <col width="200" />
                    <col width="1*" />
                </colgroup>
                <?php foreach($this->shipment->getMethods() as $method) {
                /* @var $method Ajde_Shop_Shipping_Method */ ?>
                    <tr>
                        <td>
                            <input type='radio' name='shipment_method' <?php if ($this->method == $method->getName()) { echo 'checked=\'checked\''; } ?>value='<?php echo esc($method->getName()); ?>' id='<?php echo esc($method->getName()); ?>' />
                        </td>
                        <td>
                            <label for='<?php echo esc($method->getName()); ?>'>
                                <?php echo clean($method->getDescription()); ?>
                            </label>
                        </td>
                        <td>
                            <?php echo esc($method->getFormattedTotal()); ?>
                        </td>
                    </tr>
                <?php } ?>
            </table>

        </div>
    </div>

<?php } ?>
