<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

/* @var $transaction Ajde_Shop_Transaction */
$transaction = $this->transaction;

$this->requireCss('transaction/view.print', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="print"');
?>

<div class="container main">

    <div class="page-header">
        <div class="hidden-print btn-group pull-right">
            <a class="btn btn-primary" onclick="window.print();">
                <i class="glyphicon glyphicon-print"></i>
                <?php echo __('Print'); ?>
            </a>
            <a class="btn btn-default" href="shop/transaction:export/<?php echo $transaction->getSecret(); ?>.pdf">
                <i class="glyphicon glyphicon-file"></i>
                <?php echo __('PDF'); ?>
            </a>
        </div>

        <h2>
            <?php echo __('Order'); ?>
        </h2>
    </div>

    <?php if ($transaction->hasLoaded() === false) { ?>

        <h4><?php echo __('Order not found'); ?></h4>
        <p><a href='shop'><?php echo __('Back to shop'); ?></a></p>

    <?php } else { ?>

        <div class="row">
            <div class="col-sm-12">

                <div class="pull-right">
                    <?php echo $this->includeModule('shop/legal.body'); ?>
                </div>

                <table class="order order-table" style="margin-bottom: 50px;">
                    <tbody>
                        <tr>
                            <td><?php echo __('Order ID') ?></td>
                            <td><?php echo _e($transaction->getOrderId()); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Date') ?></td>
                            <td><?php echo _e(strftime('%e %B %Y', strtotime($transaction->added))); ?></td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">

                <table class="table table-condensed order order-table">
                    <thead>
                        <tr>
                            <th colspan="2">
                                <h4><?php echo __('Your details'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo __('Full name', 'shop') ?></td>
                            <td><?php echo _e($transaction->name); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('E-mail address', 'shop') ?></td>
                            <td><?php echo _e($transaction->email); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Address', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_address); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Zipcode', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_zipcode); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('City', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_city); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Region', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_region); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo __('Country', 'shop') ?></td>
                            <td><?php echo _e($transaction->shipment_country); ?></td>
                        </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                    <tr>
                        <th>
                            <h4><?php echo __('Your comment'); ?></h4>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="left">
                            <?php echo _e($transaction->comment); ?>
                        </td>
                    </tr>
                    </tbody>
                </table>

            </div>
            <div class="col-sm-6">

                <table class="table table-condensed order">
                    <thead>
                    <tr>
                        <th>
                            <h4><?php echo __('Order'); ?></h4>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class='summary'>
                            <?php echo _c($transaction->shipment_description); ?>
                        </td>
                    </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                        <tr>
                            <th>
                                <h4><?php echo __('Shipment method'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="left">
                                <?php
                                if ($shipping = $transaction->getShipping()->getCurrentMethod()) {
                                    echo _c($shipping->getDescription());
                                    echo "<span class='pull-right'>" . $transaction->getFormattedShippingTotal() . "</span>";
                                } ?>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                        <tr>
                            <th>
                                <h4><?php echo __('Status'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="left">
                                <?php switch($transaction->payment_status) {
                                    case 'pending':
                                        if (!($this->source == 'session' && $transaction->payment_status == 'pending')) { ?>
                                            <p>
                                                <a href="shop/transaction:resetPayment/<?php echo $transaction->getSecret(); ?>.html" class="btn btn-info btn-sm pull-right">
                                                    <span class="glyphicon glyphicon-repeat"></span>
                                                    <?php echo __('Pay now'); ?>
                                                </a>
                                                <?php echo __('Not paid'); ?>
                                            </p>
                                            <?php
                                        } else {
                                            echo __('Not paid');
                                        }
                                        break;
                                    case 'requested':
                                    case 'refused':
                                    case 'cancelled': ?>
                                        <p>
                                            <?php echo __('paymentStatus' . ucfirst($transaction->payment_status)); ?>.
                                            <?php echo __('You can make a new payment for this order.') ?>
                                        </p>
                                        <p>
                                            <a href="shop/transaction:resetPayment/<?php echo $transaction->getSecret(); ?>.html" class="btn btn-info">
                                                <span class="glyphicon glyphicon-repeat"></span>
                                                <?php echo __('Retry payment'); ?>
                                            </a>
                                        </p>
                                        <?php
                                        break;
                                    case 'completed': ?>

                                        <p>
                                            <img src='<?php echo _e($transaction->getProvider()->getLogo()); ?>' width='75' style='vertical-align: middle;' class="pull-right" />
                                            <?php echo __('Paid'); ?> <?php echo __('with'); ?>
                                            <?php echo $transaction->getProvider()->getName(); ?>
                                        </p>

                                        <?php break;
                                } ?>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

        <?php if ($this->source == 'session' && $transaction->payment_status == 'pending') { ?>
            <div class='toolbar hidden-print'>
                <a href='shop/transaction:setup' class='btn btn-success btn-lg pull-right'>
                    <?php echo __('Continue with order'); ?>
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
                <a href='shop/transaction:cancel' class="btn btn-danger"><?php echo __('Cancel order'); ?></a>
                <?php echo __('or'); ?>
                <a href='shop'><?php echo __('continue shopping'); ?></a>
            </div>
        <?php } elseif ($this->source == 'session' && $transaction->payment_status == 'refused') { ?>
            <div class='toolbar hidden-print'>
                <a href='shop/transaction:resetPayment' class='btn btn-success btn-lg pull-right'>
                    <?php echo __('Reset payment and try again'); ?>
                </a>
                <a href='shop/transaction:cancel' class="btn btn-danger"><?php echo __('Cancel order'); ?></a>
            </div>
        <?php } ?>

    <?php } ?>

</div>