<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

/* @var $transaction Ajde_Shop_Transaction */
$transaction = $this->transaction;

$this->requireCss('transaction/view.print', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="print"');
?>

<div class="container main">

    <div class="page-header">
        <div class="hidden-print btn-group pull-right">
            <a class="btn btn-primary" onclick="window.print();">
                <i class="glyphicon glyphicon-print"></i>
                <?php echo trans('Print'); ?>
            </a>
            <a class="btn btn-default" href="shop/transaction:export/<?php echo $transaction->getSecret(); ?>.pdf">
                <i class="glyphicon glyphicon-file"></i>
                <?php echo trans('PDF'); ?>
            </a>
        </div>

        <h2>
            <?php echo trans('Order'); ?>
        </h2>
    </div>

    <?php if ($transaction->hasLoaded() === false) { ?>

        <h4><?php echo trans('Order not found'); ?></h4>
        <p><a href='shop'><?php echo trans('Back to shop'); ?></a></p>

    <?php } else { ?>

        <div class="row">
            <div class="col-sm-12">

                <div class="pull-right">
                    <?php echo $this->includeModule('shop/legal.body'); ?>
                </div>

                <table class="order order-table" style="margin-bottom: 50px;">
                    <tbody>
                        <tr>
                            <td><?php echo trans('Order ID') ?></td>
                            <td><?php echo esc($transaction->getOrderId()); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo trans('Date') ?></td>
                            <td><?php echo esc(strftime('%e %B %Y', strtotime($transaction->added))); ?></td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

        <div class="row">
            <div class="col-sm-6">

                <table class="table table-condensed order order-table">
                    <thead>
                        <tr>
                            <th colspan="2">
                                <h4><?php echo trans('Your details'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo trans('Full name', 'shop') ?></td>
                            <td><?php echo esc($transaction->name); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo trans('E-mail address', 'shop') ?></td>
                            <td><?php echo esc($transaction->email); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo trans('Address', 'shop') ?></td>
                            <td><?php echo esc($transaction->shipment_address); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo trans('Zipcode', 'shop') ?></td>
                            <td><?php echo esc($transaction->shipment_zipcode); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo trans('City', 'shop') ?></td>
                            <td><?php echo esc($transaction->shipment_city); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo trans('Region', 'shop') ?></td>
                            <td><?php echo esc($transaction->shipment_region); ?></td>
                        </tr>
                        <tr>
                            <td><?php echo trans('Country', 'shop') ?></td>
                            <td><?php echo esc($transaction->shipment_country); ?></td>
                        </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                    <tr>
                        <th>
                            <h4><?php echo trans('Your comment'); ?></h4>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="left">
                            <?php echo esc($transaction->comment); ?>
                        </td>
                    </tr>
                    </tbody>
                </table>

            </div>
            <div class="col-sm-6">

                <table class="table table-condensed order">
                    <thead>
                    <tr>
                        <th>
                            <h4><?php echo trans('Order'); ?></h4>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class='summary'>
                            <?php echo clean($transaction->shipment_description); ?>
                        </td>
                    </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                        <tr>
                            <th>
                                <h4><?php echo trans('Shipment method'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="left">
                                <?php
                                if ($shipping = $transaction->getShipping()->getCurrentMethod()) {
                                    echo clean($shipping->getDescription());
                                    echo "<span class='pull-right'>" . $transaction->getFormattedShippingTotal() . "</span>";
                                } ?>
                            </td>
                        </tr>
                    </tbody>
                </table>

                <table class="table table-condensed order">
                    <thead>
                        <tr>
                            <th>
                                <h4><?php echo trans('Status'); ?></h4>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="left">
                                <?php switch($transaction->payment_status) {
                                    case 'pending':
                                        if (!($this->source == 'session' && $transaction->payment_status == 'pending')) { ?>
                                            <p>
                                                <a href="shop/transaction:resetPayment/<?php echo $transaction->getSecret(); ?>.html" class="btn btn-info btn-sm pull-right">
                                                    <span class="glyphicon glyphicon-repeat"></span>
                                                    <?php echo trans('Pay now'); ?>
                                                </a>
                                                <?php echo trans('Not paid'); ?>
                                            </p>
                                            <?php
                                        } else {
                                            echo trans('Not paid');
                                        }
                                        break;
                                    case 'requested':
                                    case 'refused':
                                    case 'cancelled': ?>
                                        <p>
                                            <?php echo trans('paymentStatus' . ucfirst($transaction->payment_status)); ?>.
                                            <?php echo trans('You can make a new payment for this order.') ?>
                                        </p>
                                        <p>
                                            <a href="shop/transaction:resetPayment/<?php echo $transaction->getSecret(); ?>.html" class="btn btn-info">
                                                <span class="glyphicon glyphicon-repeat"></span>
                                                <?php echo trans('Retry payment'); ?>
                                            </a>
                                        </p>
                                        <?php
                                        break;
                                    case 'completed': ?>

                                        <p>
                                            <img src='<?php echo esc($transaction->getProvider()->getLogo()); ?>' width='75' style='vertical-align: middle;' class="pull-right" />
                                            <?php echo trans('Paid'); ?> <?php echo trans('with'); ?>
                                            <?php echo $transaction->getProvider()->getName(); ?>
                                        </p>

                                        <?php break;
                                } ?>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>

        <?php if ($this->source == 'session' && $transaction->payment_status == 'pending') { ?>
            <div class='toolbar hidden-print'>
                <a href='shop/transaction:setup' class='btn btn-success btn-lg pull-right'>
                    <?php echo trans('Continue with order'); ?>
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
                <a href='shop/transaction:cancel' class="btn btn-danger"><?php echo trans('Cancel order'); ?></a>
                <?php echo trans('or'); ?>
                <a href='shop'><?php echo trans('continue shopping'); ?></a>
            </div>
        <?php } elseif ($this->source == 'session' && $transaction->payment_status == 'refused') { ?>
            <div class='toolbar hidden-print'>
                <a href='shop/transaction:resetPayment' class='btn btn-success btn-lg pull-right'>
                    <?php echo trans('Reset payment and try again'); ?>
                </a>
                <a href='shop/transaction:cancel' class="btn btn-danger"><?php echo trans('Cancel order'); ?></a>
            </div>
        <?php } ?>

    <?php } ?>

</div>
