<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="container main">

    <div class="page-header">
        <h2><?php echo trans('Edit shopping cart', 'shop'); ?></h2>
    </div>

    <?php echo $this->ACAjaxForm('shop/cart:edit', null, 'editCart', 'body'); ?>

        <input type='hidden' name='update' value='1' />

        <table class='cart'>
            <colgroup>
                <col />
                <col width="100" />
                <col width="200" />
                <col width="150" />
                <col width="50" />
            </colgroup>
            <thead>
                <tr>
                    <th><?php echo trans('Product', 'shop'); ?></th>
                    <th><?php echo trans('Price', 'shop'); ?></th>
                    <th><?php echo trans('Quantity', 'shop'); ?></th>
                    <th><?php echo trans('Total incl. VAT', 'shop'); ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->items->length() === 0) { ?>
                    <tr>
                        <td colspan='4'>
                            <?php echo trans('Your cart is empty', 'shop'); ?><br/>
                            <a href='shop'><?php echo trans('To the shop', 'shop'); ?></a>
                        </td>
                    </tr>
                <?php } ?>
                <?php foreach($this->items as $item) {
                    /* @var $item CartItemModel */ ?>
                    <tr>
                        <td>
                            <a href='<?php echo $item->getEntity()->getSlug(); ?>'>
                                <?php echo $item->getDescription(); ?>
                            </a>
                        </td>
                        <td>€ <?php echo money_format('%!i', $item->getUnitprice() * (1+$item->getVATPercentage())); ?></td>
                        <td>
                            <input type='number' class='qty' name='qty[<?php echo $item->getPK(); ?>]' value='<?php echo $item->getQty(); ?>' />
                            <input type='button' value='<?php echo trans('Update', 'shop'); ?>' class="btn btn-default btn-sm" />
                        </td>
                        <td><?php echo $item->getFormattedTotal(); ?></td>
                        <td><a href='javascript:void(0);' class='delete btn btn-danger btn-sm' data-id='<?php echo $item->getPK(); ?>'><?php echo trans('delete'); ?></a></td>
                    </tr>
                <?php } ?>
                <tfoot>
                    <tr>
                        <td colspan='2'><?php echo trans('Total', 'shop'); ?></td>
                        <td></td>
                        <td><?php echo $this->items->getFormattedTotal(); ?></td>
                        <td></td>
                    </tr>
                </tfoot>
            </tbody>
        </table>

        <?php if ($this->items->length() !== 0) { ?>
            <div class='toolbar text-right'>
                <a class='btn btn-success btn-lg' href='shop/checkout'>
                    <?php echo trans('Checkout', 'shop'); ?>
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        <?php } ?>

    </form>

</div>
