<p>
	Please <a href="http://www.google.com/support/accounts/bin/answer.py?&answer=61416">enable cookies</a> to view this website
</p>
<p>
	<a href="//<?php echo Config::get('site_root'); echo $this->returnto; ?>">Try again</a>
</p>
<script>
if (typeof history.replaceState !== 'undefined') {
	history.replaceState('', 'root', '//<?php echo Config::get('site_root'); echo $this->returnto; ?>');
}
</script>