<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<h2><?php echo __("Welcome to Creactor"); ?></h2>
<p>
	Yet another PHP 5.0 MVC framework with out-of-the-box HTML / CSS / JS / caching and HTTP optimizations. Your project will be fast and cutting edges right from the start!
</p>
<p>
	<?php if (Config::getInstance()->getParentClass() == 'advanced') { ?>
	<a class='action' href='site/create'>
		<?php echo __("Create site"); ?>
	</a>
	<?php } ?>
	<a class='action' href='template/browse'>
		<?php echo __("Browse templates"); ?>
	</a>	
</p>