<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

// Fancybox
$this->requireJsPublic('_core/crud/fancybox/jquery.fancybox.pack.js');
$this->requireCssPublic('_core/crud/fancybox/jquery.fancybox.css');

// Fancybox thumb helper
$this->requireJsPublic('_core/crud/fancybox/helpers/jquery.fancybox-thumbs.js');
$this->requireCssPublic('_core/crud/fancybox/helpers/jquery.fancybox-thumbs.css');

// Lazyload
$this->requireJsPublic('_core/crud/jquery.lazyload.min.js');

/* @var $field Ajde_Crud_Field_File */
$field = $this->field;
?>

<div class='fileupload <?php if ($field->getValue()) { echo 'visuallyhidden'; } ?>'>
	
	<?php 
	$options = array(
		'saveDir' => $field->getSaveDir(),
		'extensions' => $field->getExtensions(),
		'multiple' => $field->getMultiple()
	);
	echo $this->ACAjaxUpload($field->getName(), $options); ?>
	
	<div class='filebrowser'>
		<a href='javascript:void(0);' class='toggleFileBrowser'><?php echo _e('Choose existing'); ?></a>
		<div class='browser'>
			<?php
			$filelist = Ajde_FS_Find::findFiles($field->getSaveDir(), "{*." . implode(',*.', $field->getExtensions()) . "}", GLOB_BRACE);
			$exclude = preg_grep("/_[0-9]+x[0-9]+c?/i", $filelist);
			foreach($filelist as $file) {
				if (in_array($file, $exclude)) {
					continue;
				}
				$extension = pathinfo($file, PATHINFO_EXTENSION);
				echo "<a href='javascript:void(0);'>";										
					if ($isImage = in_array(strtolower($extension), array('jpg', 'jpeg', 'png', 'gif'))) {
						// Don't use $this->ACImage() to support lazy loading
						$image = new Ajde_Resource_Image($file);
						$image->setWidth(50);
						$image->setHeight(50);
						$image->setCrop(true);							
						echo "<img class='thumb' data-original='" . $image->getLinkUrl() . "' src='public/images/gray.gif' width='50' height='50' />";
					
					} else {
						echo "<span class='icon'><img class='icon' src='" . Ajde_Resource_FileIcon::_($extension) . "' /></span>";
					}
					echo "<span>";
						echo "<span class='filename'>" . str_replace(Config::get('local_root') . '/' . $field->getSaveDir(), '', $file) . "</span>";
						if ($isImage) {
							echo "<span class='imagePreview preview' data-fancybox-group='preview" . ucfirst($field->getName()) . "' title='" . _e(str_replace(Config::get('local_root') . '/' . $field->getSaveDir(), '', $file)) . "' href='" . $this->escape(str_replace(Config::get('local_root') . '/', '', $file)) . "'>preview</span>";
						} else {
							echo "<span class='filePreview preview' href='" . $this->escape(str_replace(Config::get('local_root') . '/', '', $file)) . "'>preview</span>";
						}
					echo "</span>";
				echo "</a>";
			}
			?>
			<div class='clearfix'></div>
		</div>
	</div>

</div>

<?php

if ($field->getValue()) {
	$extension = pathinfo($field->getValue(), PATHINFO_EXTENSION); ?>

	<div class='filelist'>
		
		<input
			<?php echo $field->getHtmlAttributes(); ?>
		/>
		
		<?php
		if ($isImage = in_array(strtolower($extension), array('jpg', 'jpeg', 'png', 'gif'))) {
			$thumbDim = $field->hasThumbDim() ? $field->getThumbDim() : array('width' => 150, 'height' => 150); ?>
			<a class='imagePreview img' title='<?php echo _e($field->getValue()); ?>' href='<?php echo $field->getSaveDir() . $field->getValue(); ?>' target='_blank'>
				<?php echo $this->ACImage(array(
						'filename' => $field->getSaveDir() . $field->getValue(),
						'width' => $thumbDim['width'],
						'height' => $thumbDim['height'],
						'crop' => true
					)); ?>
			</a>
			<br/>
		<?php } ?>

		<span>
			<img class='icon' src='<?php echo Ajde_Resource_FileIcon::_($extension); ?> ' />
			<?php if ($isImage) { ?>
				<a class='imagePreview preview' title='<?php echo _e($field->getValue()); ?>' href='<?php echo $field->getSaveDir() . $field->getValue(); ?>' target='_blank'><?php echo $field->getValue(); ?></a>
			<?php } else { ?>
				<a class='filePreview preview' href='<?php echo $field->getSaveDir() . $field->getValue(); ?>' target='_blank'><?php echo $field->getValue(); ?></a>
			<?php } ?>
			<a href='#' class='deleteFileCrud'>delete</a> 
		</span>
			
	</div>
		
<?php } ?>