<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireJsPublic('_core/crud/fancybox/jquery.fancybox.pack.js');
$this->requireCssPublic('_core/crud/fancybox/jquery.fancybox.css');
/* @var $field Ajde_Crud_Field_Multiple */
$field = $this->field;
?>

<div
	class='multiple'
	data-edit-route='<?php echo $field->getEditRoute(); ?>'
	data-field='<?php echo $field->getName(); ?>'
	data-parent='<?php echo (string) $field->getCrud()->getModel()->getTable(); ?>'
	data-parent-id='<?php echo $field->getCrud()->getModel()->getPK(); ?>'
	data-dynamic='<?php echo ($field->hasTableFields() ? '1' : '0'); ?>'
>

	<div class='multipleToolbar'>
		<a href='javascript:void(null);' class='button new newMultiple' data-select='<?php echo $field->getName(); ?>'>New</a>
		<?php if ($field->hasCrossReferenceTable()) { ?>
			or connect existing:
			<select name='<?php echo $field->getName(); ?>'>
				<option value=''>(choose)</option>					
				<?php foreach($field->getValues() as $model) { 
					/* @var $model Ajde_Model */ ?>
					<option value='<?php echo $model->getPK(); ?>'>
						<?php echo $model->get($model->getDisplayField()); ?>
					</option>
				<?php } ?>
			</select>
			<a href='javascript:void(null);' class='button add addMultiple'>Add</a>
		<?php } ?>
	</div>

	<?php $this->requireCss('crud/list'); ?>

	<table class='crudList multipleList'>
		<thead>
			<tr>
				<th></th>
				<th class='main'><?php echo $field->getModel()->getTable()->getFieldProperties($field->getModel()->getDisplayField(), 'label'); ?></th>
				<?php if ($field->hasTableFields()) {
					foreach ($field->getTableFields() as $extraField) { ?>
						<th><?php echo $field->getModel()->getTable()->getFieldProperties($extraField['name'], 'label'); ?></th>
					<?php } 
				} ?>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<tr class='template'>
				<td></td>
				<td class='main'></td>
				<?php if ($field->hasTableFields()) {
					foreach ($field->getTableFields() as $extraField) { ?>
						<td></td>
					<?php } 
				} ?>
				<td class='buttons'>
					<a href='javascript:void(null);' class='editMultiple' data-id=''>edit</a>
					<a href='javascript:void(null);' class='deleteMultiple' data-id=''>delete</a>
				</td>
			</tr>
			<?php foreach($field->getChildren() as $child) {
				/* @var $child Ajde_Model */ ?>
				<tr data-id='<?php echo $child->getPK(); ?>'>
					<td><?php echo $child->getPK(); ?></td>
					<td class='main'><?php echo $child->get($child->getDisplayField()); ?></td>
					<?php if ($field->hasTableFields()) {
						foreach ($field->getTableFields() as $extraField) { 
							$value	= $child->get($extraField['name']);
							$type	= $extraField['type'];
							if ($type == 'file' && $value) { ?>
								<td>
									<?php
									$extension = pathinfo($value, PATHINFO_EXTENSION);
									if ($isImage = in_array(strtolower($extension), array('jpg', 'jpeg', 'png', 'gif'))) {
										$thumbDim = $field->hasThumbDim() ? $field->getThumbDim() : array('width' => 75, 'height' => 75); ?>
										<a class='imagePreview img' title='<?php echo _e($value); ?>' href='<?php echo $extraField['saveDir'] . $value; ?>' target='_blank'>
											<?php echo $this->ACImage(array(
													'filename' => $extraField['saveDir'] . $value,
													'width' => $thumbDim['width'],
													'height' => $thumbDim['height'],
													'crop' => true
												)); ?>
										</a>									
									<?php } else { ?>
										<img class='icon' src='<?php echo Ajde_Resource_FileIcon::_($extension); ?> ' />
										<a class='filePreview preview' href='<?php echo $extraField['saveDir'] . $value; ?>' target='_blank'><?php echo $value; ?></a>
									<?php } ?>
								</td>
							<?php } else { ?>
								<td><?php echo $child->get($extraField['name']); ?></td>
							<?php }
						} 
					} ?>
					<td class='buttons'>
						<a href='javascript:void(null);' class='editMultiple' data-id='<?php echo $child->getPK(); ?>'>edit</a>
						<a href='javascript:void(null);' class='deleteMultiple' data-id='<?php echo $child->getPK(); ?>'>
							<?php echo ($field->hasCrossReferenceTable()) ? 'disconnect' : 'delete'; ?>
						</a>
					</td>
				</tr>	
			<?php } ?>
		</tbody>
	</table>
	
</div>