<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo Config::get('ident'); ?>'>
	<head>
		<meta charset='utf-8'>
		<!--[if IE]><![endif]-->		
		<title><?php echo Config::get('sitename'); ?></title>
		<?php echo Ajde::app()->getDocument()->getHead('css'); ?>
	</head>
	<!--[if lt IE 7 ]> <body class='ie6'> <![endif]-->
	<!--[if IE 7 ]>    <body class='ie7'> <![endif]-->
	<!--[if IE 8 ]>    <body class='ie8'> <![endif]-->
	<!--[if IE 9 ]>    <body class='ie9'> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		<div id='wrapper'>						
			<?php echo Ajde::app()->getDocument()->getBody(); ?>				
		</div>
		<?php echo Ajde::app()->getDocument()->getScripts(); ?>		
	</body>
</html>