<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

// Twitter bootstrap
$this->requireCssTop('bootstrap-responsive');
$this->requireCssTop('bootstrap-cosmo');

// Include jQuery 1.7
$this->requireJsLibrary('jquery', '1.7');

// Bootstrap.js
$this->requireJs('bootstrap.min');

// EU cookie law
$this->requireJsPublic('lib/cookie.debug.min.js'); $this->requireCssPublic('lib/cookie_style.css'); // @see http://creativeaura.github.com/eu-cookie-opt-in/
$this->requireJs('core.cookielaw');

// Some JavaScript i18n
$this->requireJsFirst('i18n.' . Ajde_Lang::getInstance()->getShortLang());

// Alert bar
$this->requireJsFirst('core.alert'); $this->requireCssFirst('core.alert');

?>
<!-- Inspired by HTML5 Boilerplate -->
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo Config::get('ident'); ?>' data-lifetime='<?php echo (Config::get('sessionLifetime') == 0 ? 180 : Config::get('sessionLifetime')); ?>' data-alert='<?php echo _e(Ajde_Session_Flash::get('alert')); ?>'>
	<head>
		
		<!-- UTF-8 please (also in the headers, just to be sure) -->
		<meta charset='utf-8'>
		
		<!-- Some content meta tags -->
		<title><?php echo _e(Ajde::app()->getDocument()->getFullTitle()); ?></title>		
		<meta name='description' content='<?php echo _e(Ajde::app()->getDocument()->getDescription()); ?>' />
		<meta name='author' content='<?php echo _e(Config::get('author')); ?>' />
		<?php echo Ajde::app()->getDocument()->getMeta(); ?>
		
		<!-- Mobile presentation meta tags -->
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">
		<meta name="viewport" content="width=device-width">
		<meta http-equiv="cleartype" content="on">
		
		<!-- Define the root of the site -->
		<base href='http://<?php echo Config::get('lang_root'); ?>' />
		
		<!-- require JavaScript and cookies -->		
		<noscript>
			<meta http-equiv="refresh" content="0;url=main/nojavascript.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>" />
		</noscript>				
		<script defer="defer">
			if (navigator.cookieEnabled === false) {
				document.location.href='main/nocookies.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>';
			}
		</script>
		
		<!-- Make IE6-8 HTML5 compliant, somewhat... -->
		<!--[if lt IE 9]>
		<script src='public/js/lib/html5shiv.js'></script>
		<![endif]-->
		
		<!-- Favicon and CSS -->
		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		<?php echo $this->getDocument()->getHead('css'); ?>
		
	</head>
	
	<!-- Target older versions of IE with CSS classes -->
	<!--[if lt IE 7 ]> <body class='ie6 oldie'> <![endif]-->
	<!--[if IE 7 ]>    <body class='ie7 oldie'> <![endif]-->
	<!--[if IE 8 ]>    <body class='ie8 oldie'> <![endif]-->
	<!--[if IE 9 ]>    <body class='ie9'> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container-fluid">
					<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
					</button>
					<a class="brand" href="#">Ajde Framework</a>
					<div class="nav-collapse collapse">
						<p class="navbar-text pull-right">
							Logged in as <a href="#" class="navbar-link">Username</a>
						</p>
						<ul class="nav">
							<li class="active"><a href="#">Home</a></li>
							<li><a href="#about">About</a></li>
							<li><a href="#contact">Contact</a></li>
						</ul>
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>

		<div class="container-fluid">
			<div class="row-fluid">
				<div class="span3">
					<div class="well sidebar-nav">
						<ul class="nav nav-list">
							<li class="nav-header">Sidebar</li>
							<li class="active"><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li class="nav-header">Sidebar</li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li class="nav-header">Sidebar</li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
							<li><a href="#">Link</a></li>
						</ul>
					</div><!--/.well -->
				</div><!--/span-->
			<div class="span9">
				<div class="hero-unit">
					<h1><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></h1>
					<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
					<p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
				</div>
				<div class="row-fluid">
					<div class="span4">
						<h2>Heading</h2>
						<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
						<p><a class="btn" href="#">View details &raquo;</a></p>
					</div><!--/span-->
					<div class="span4">
						<h2>Heading</h2>
						<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
						<p><a class="btn" href="#">View details &raquo;</a></p>
					</div><!--/span-->
					<div class="span4">
						<h2>Heading</h2>
						<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
						<p><a class="btn" href="#">View details &raquo;</a></p>
					</div><!--/span-->
				</div><!--/row-->
			</div><!--/span-->
		</div><!--/row-->

		<hr>

		<footer>
		  <p>&copy; Company 2013</p>
		</footer>

	</div><!--/.fluid-container-->
		
		<!-- The content -->
		<header class='container'>
			<div class='row'>
				<div class='twelvecol'>
					<h4 class='branding'></h4>
					<h1></h1>
				</div>
			</div>
		</header>
		
		<div class='container'>
			<div class='row'>
				<nav class='twelvecol'>
					<?php echo $this->includeModule('admin/menu'); ?>
				</nav>				
			</div>
			<div class='row'>
				<article class='twelvecol'>
					<?php echo $this->getDocument()->getBody(); ?>
				</article>
			</div>
		</div>
		
		<footer class='container'>
			<div class='row'>
				<div class='twelvecol'>
					&copy; <?php echo date('Y'); ?> <?php echo Config::get('author'); ?><br/>
					<a href='javascript:EU.CookiePreferenceUI.toggleOptions();void(0);'><?php echo __('Change cookie settings'); ?></a>
				</div>
			</div>
		</footer>
		
		<!-- The scripts -->
		<?php echo $this->getDocument()->getScripts(); ?>
		
		<!-- Google Analytics -->
		<script type="text/javascript">
		if (EU.Cookie.hasSubscribed()) {
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-XXXXX-X']);
			_gaq.push(['_trackPageview']);
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		}
		</script>
		
		<!-- updatemybrowser.org widget -->
		<script type="text/javascript">
		(function() {
			var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true;
			s.src = ('https:'==document.location.protocol?'https://':'http://') + 'updatemybrowser.org/umb.js';
			var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(s, b);
		})();	
		</script>
		
	</body>
</html>

<!-- Some debugging info -->
<!--[<pre>
	<?php $version = Config::get('version'); echo Config::get('ident') . ', v' . $version['number'] . ' (' . $version['name'] . ')'; ?> 
	Cache <?php echo Ajde_Cache::getInstance()->isEnabled() ? 'enabled' : 'disabled' ?> 
	Last modified on <?php echo date("r", Ajde_Cache::getInstance()->getLastModified()); ?> 
</pre><![-->