<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

// Include jQuery 1.7
$this->requireJsLibrary('jquery', '1.7');

// Twitter Bootstrap
$this->requireCssPublic('bootstrap/bootstrap3.min.css');
$this->requireJsPublic('bootstrap/bootstrap3.min.js');

// Some JavaScript i18n
$this->requireJsFirst('i18n.' . Ajde_Lang::getInstance()->getShortLang());

// Alert bar
$this->requireJsFirst('core.alert');
$this->requireCssFirst('core.alert');

// Example styles
$this->requireGWebFont('PT Sans Narrow', array(400));
$this->requireGWebFont('Roboto', array(400, 700));

?>

<!DOCTYPE html>
<html
	lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>'
	id='<?php echo Config::get('ident'); ?>'
	data-lifetime='<?php echo (Config::get('sessionLifetime') == 0 ? 180 : Config::get('sessionLifetime')); ?>'
	data-alert='<?php echo _e(Ajde_Session_Flash::get('alert')); ?>'>
	
	<head>
	
		<!-- UTF-8 please (also in the headers, just to be sure) -->
		<meta charset='utf-8'>
		
		<!-- Document title -->
		<title><?php echo _e(Ajde::app()->getDocument()->getFullTitle()); ?></title>
				
		<!-- Some content meta tags -->
		<meta name='description' content='<?php echo _e(Ajde::app()->getDocument()->getDescription()); ?>' />
		<meta name='author' content='<?php echo _e(Config::get('author')); ?>' />
		<?php echo Ajde::app()->getDocument()->getMeta(); ?>
		
		<!-- Mobile presentation meta tags -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- Define the root of the site -->
		<base href='http://<?php echo Config::get('lang_root'); ?>' />
		
		<!-- require JavaScript and cookies -->		
		<noscript>
			<meta http-equiv="refresh" content="0;url=main/nojavascript.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>" />
		</noscript>				
		<script defer="defer">
			if (navigator.cookieEnabled === false) {
				document.location.href='main/nocookies.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>';
			}
		</script>
		
		<!-- Make IE6-8 HTML5 compliant, somewhat... -->
		<!--[if lt IE 9]>
			<script src='public/js/lib/html5shiv.js'></script>
		<![endif]-->
		
		<!-- Favicon -->
		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		
		<!-- Stylesheets -->
		<?php echo $this->getDocument()->getHead('css'); ?>

		<!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
		<link rel="stylesheet" type="text/css" href="http://assets.cookieconsent.silktide.com/current/style.min.css"/>
		<script type="text/javascript" src="http://assets.cookieconsent.silktide.com/current/plugin.min.js"></script>
		<script type="text/javascript">
		// <![CDATA[
		cc.initialise({
			cookies: {
				social: {},
				analytics: {},
				advertising: {},
				necessary: {}
			},
			settings: {
				consenttype: "implicit",
				style: "light",
				bannerPosition: "bottom",
				hideprivacysettingstab: true,
				onlyshowbanneronce: true,
				disableallsites: true
			}
		});
		// ]]>
		</script>
		<!-- End Cookie Consent plugin -->
				
		<!-- End Cookie Consent plugin -->
		
	</head>

	<!-- Target older versions of IE with CSS classes -->
	<!--[if lt IE 7 ]> <body class='ie6 oldie'> <![endif]-->
	<!--[if IE 7 ]>    <body class='ie7 oldie'> <![endif]-->
	<!--[if IE 8 ]>    <body class='ie8 oldie'> <![endif]-->
	<!--[if IE 9 ]>    <body class='ie9'> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		
		<!--  Bootstrap navbar -->	
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"><?php echo _e(Config::get('sitename')); ?></a>
				<div class="nav-collapse collapse">
					<ul class="nav navbar-nav">
						<?php
						Ajde_Model::register('admin');
						Ajde_Model::register('node');
						
						$menu = new MenuModel();
						$menu->loadByName('mainmenu');
						foreach($menu->getLinks() as $link) { ?>						
							<li><a href='<?php echo _e($link->getUrl()); ?>'><?php echo _e($link->getName()); ?></a></li>
						<?php } ?>
					</ul>
				</div>
			</div>
		</div>
		
		<!-- Page content -->
		<div class="container main">
			<?php echo $this->getDocument()->getBody(); ?>
		</div>
				
		<footer class='container'>
			<div class='col-12'>
				&copy; <?php echo date('Y'); ?> <?php echo Config::get('author'); ?>
			</div>
		</footer>
		
		<!-- The scripts -->
		<?php echo $this->getDocument()->getScripts(); ?>
		
		<!-- Google Analytics -->
		<script type="text/javascript" class="cc-onconsent-analytics">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-XXXXX-X']);
		_gaq.push(['_trackPageview']);
		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
		</script>
		
		<!-- updatemybrowser.org widget -->
		<script type="text/javascript">
		(function() {
			var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true;
			s.src = ('https:'==document.location.protocol?'https://':'http://') + 'updatemybrowser.org/umb.js';
			var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(s, b);
		})();	
		</script>
		
	</body>
</html>

<!-- Some debugging info -->
<!--[<pre>
	<?php $version = Config::get('version'); echo Config::get('ident') . ', v' . $version['number'] . ' (' . $version['name'] . ')'; ?> 
	Cache <?php echo Ajde_Cache::getInstance()->isEnabled() ? 'enabled' : 'disabled' ?> 
	Last modified on <?php echo date("r", Ajde_Cache::getInstance()->getLastModified()); ?> 
</pre><![-->