<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ ?>

<div class="container">
    <div class="row-fluid">
        <?php echo $this->includeModule('user/menu'); ?>
        <div class="span9 col-sm-9">

            <div class='page-header'>
                <?php echo $this->user->displayGravatar(90, 'pull-left'); ?> &nbsp;
                <h1> &nbsp; <?php echo $this->clean($this->user->getFullname()); ?></h1>
            </div>

            <dl class="dl-horizontal">
                <dt>E-mail address</dt>
                <dd><?php echo $this->clean($this->user->getEmail()); ?></dd>

                <dt>Full name</dt>
                <dd><?php echo $this->clean($this->user->getFullname()); ?></dd>
            </dl>
        </div>
    </div>
</div>
