<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$this->requireJsPublic('core/complexify/jquery.complexify.banlist.js');
$this->requireJsPublic('core/complexify/jquery.complexify.min.js');

?>

<div class="container">
    <div class="row-fluid">
        <?php echo $this->includeModule('user/menu'); ?>
        <div class="span9 col-sm-9">

            <div class='page-header'>
                <?php echo $this->user->displayGravatar(90, 'pull-left'); ?> &nbsp;
                <h1> &nbsp; Settings</h1>
            </div>

            <?php echo $this->ACAjaxForm('user/settings', 'settingsform', 'form-horizontal'); ?>
                <fieldset>
                    <legend><?php echo __('Change my account settings'); ?></legend>

                    <div class="control-group give-status">
                        <div class="controls">
                            <p class="help-block status-text">&nbsp;</p>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="in_user"><?php echo __(ucfirst($this->user->usernameField)); ?></label>
                        <div class="controls">
                            <input type="text" name="<?php echo $this->user->usernameField; ?>" placeholder="" required id="in_user" value='<?php echo $this->escape($this->user->get($this->user->usernameField)); ?>'/>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="in_pass1">Change <?php echo __(ucfirst($this->user->passwordField)); ?></label>
                        <div class="controls">
                            <input type="password" name="password" placeholder="****" id="in_pass1" />
                            <div class='complexity'>
                                <div class='progressbar'><div class='progress'></div></div>
                                <div class='class'></div>
                            </div>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="in_pass2"><?php echo __('Verify') . ' ' . __($this->user->passwordField); ?></label>
                        <div class="controls">
                            <input type="password" name="passwordCheck" placeholder="****" id="in_pass2" />
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="in_email"><?php echo __('E-mail'); ?></label>
                        <div class="controls">
                            <input type="text" name="email" required id="in_email" value='<?php echo $this->escape($this->user->getEmail()); ?>' />
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="in_name"><?php echo __('Full name'); ?></label>
                        <div class="controls">
                            <input type="text" name="fullname" required id="in_name" value='<?php echo $this->escape($this->user->getFullname()); ?>' />
                        </div>
                    </div>

                    <div class="form-actions">
                        <button class="btn btn-warning" type="submit"><?php echo __('change'); ?></button>
                        <a class="btn btn-normal pull-right" href="user"><?php echo __('cancel'); ?></a>
                    </div>
                </fieldset>
            </form>

        </div><!--/span-->
        <div class='span4'>




        </div>
    </div>
</div>