<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$this->requireJsPublic('core/complexify/jquery.complexify.banlist.js');
$this->requireJsPublic('core/complexify/jquery.complexify.min.js');

$this->requireCssRemote("//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css");

/* @var $user UserModel */
$user = $this->user;

?>

<div class="container">
    <div class="row-fluid">
        <?php echo $this->includeModule('user/menu'); ?>
        <div class="span9 col-sm-9">

            <div class='page-header'>
                <?php echo $user->displayGravatar(90, 'pull-left'); ?> &nbsp;
                <h1> &nbsp; Social</h1>
            </div>

            <?php
            $model = new SsoModel();
            $hasPassword = $user->hasPassword();
            foreach($this->sso as $sso) {
                $staticClass = "Ajde_User_Sso_" . ucfirst($sso);
                $icon = call_user_func(array($staticClass, 'getIconName'));
                $color = call_user_func(array($staticClass, 'getColor'));
                ?>
                <div class="container" style="margin-bottom: 5px;">
                    <div class="row-fluid">
                        <?php if ($model->loadByFields(array(
                            'user' => $user->getPK(),
                            'provider' => $sso
                        ))) { ?>
                            <div class="span5 col-sm-5">
                                <a class="btn disabled btn-block" style="border: 0;" href="javascript:void(null);">
                                    <i class="fa fa-<?php echo $icon; ?> pull-left"></i> connect with <?php echo ucfirst($sso); ?>
                                </a>
                            </div>
                            <div class="span7 col-sm-7">
                                Connected as <?php echo _e($model->getUsername()); ?>.
                                <?php if ($hasPassword) { ?>
                                    <a href="user/sso:disconnect?returnto=<?php echo _e( $_GET['_route'] ); ?>&amp;provider=<?php echo $sso; ?>">Disconnect</a>.
                                <?php } else { ?>
                                    <a href="user/settings">Set password</a> first to disconnect.
                                <?php } ?>
                            </div>
                        <?php } else { ?>
                            <div class="span5 col-sm-5">
                                <a class="btn btn-primary btn-block" style="border: 0; background-color: #<?php echo $color; ?>;" href="user/sso:login?returnto=<?php echo _e( $_GET['_route'] ); ?>&amp;provider=<?php echo $sso; ?>">
                                    <i class="fa fa-<?php echo $icon; ?> pull-left"></i> connect with <?php echo ucfirst($sso); ?>
                                </a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>

        </div><!--/span-->
        <div class='span4'>

        </div>
    </div>
</div>