<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

$this->requireGWebFont('Roboto', array(300, 500, 700));

// Twitter bootstrap
$this->requireCssPublic('core/bootstrap/bootstrap-cosmo.css', Ajde_Document_Format_Html::RESOURCE_POSITION_FIRST);
$this->requireCssPublic('core/bootstrap/bootstrap-responsive.css', Ajde_Document_Format_Html::RESOURCE_POSITION_FIRST);
$this->requireCss('bootstrap');

// Dark style
//$this->requireCss('dark');

// Include jQuery 1.7
$this->requireJsLibrary('jquery', '1.7');

// Fastclick
$this->requireJsPublic('core/fastclick.js');

// Autocomplete
$this->requireJsPublic('core/jquery.autocomplete.min.js');

// Bootstrap.js
$this->requireJsPublic('core/bootstrap/bootstrap.min.js');

// jqBootstrapValidation.js
$this->requireJsPublic('core/jqBootstrapValidation.js');

// jQuery cookie
$this->requireJsPublic('core/jquery.cookie.js');

// Chosen
$this->requireJsPublic('core/chosen/chosen.jquery.min.js');
$this->requireCssPublic('core/chosen/chosen.css');
$this->requireCss('chosen');

// Picker
$this->requireJsPublic('core/picker/jquery.fs.picker.min.js');
$this->requireCssPublic('core/picker/jquery.fs.picker.css');
$this->requireCss('picker');

// CKEditor
$this->requireCss('ckeditor');

// Some JavaScript i18n
$this->requireJsFirst('i18n.' . Ajde_Lang::getInstance()->getShortLang());

// Alert bar
$this->requireJsFirst('core.alert');
$this->requireCssFirst('core.alert');

// Additional CSS
$this->requireCss('default.crud');
$this->requireCss('default.tablet', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="only screen and (max-width: 979px)"');
$this->requireCss('default.phone', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="only screen and (max-width: 767px)"');

// The user
$user = UserModel::getLoggedIn();

// Node types
Ajde_Model::register('admin');

$nodeTypes = new NodetypeCollection();
$nodeTypes->orderBy('category');
$nodeTypes->orderBy('sort');

$currentGrouper = '';

?>
<!-- Inspired by HTML5 Boilerplate -->
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo Config::get('ident'); ?>' data-lifetime='<?php echo (Config::get('sessionLifetime') == 0 ? 180 : Config::get('sessionLifetime')); ?>' data-alert='<?php echo _e(Ajde_Session_Flash::get('alert')); ?>'>
	<head>
		
		<!-- UTF-8 please (also in the headers, just to be sure) -->
		<meta charset='utf-8'>
		
		<!-- Some content meta tags -->
		<title><?php echo _e(strip_tags(Ajde::app()->getDocument()->getFullTitle())); ?></title>		
		<meta name='description' content='<?php echo _e(Ajde::app()->getDocument()->getDescription()); ?>' />
		<meta name='author' content='<?php echo _e(Config::get('author')); ?>' />
		<?php echo Ajde::app()->getDocument()->getMeta(); ?>
		
		<!-- Mobile presentation meta tags -->
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">
		<meta name="viewport" content="width=device-width">
		<meta http-equiv="cleartype" content="on">
		
		<!-- Define the root of the site -->
		<base href='http://<?php echo Config::get('lang_root'); ?>' />
		
		<!-- require JavaScript and cookies -->		
		<noscript>
			<meta http-equiv="refresh" content="0;url=main/nojavascript.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>" />
		</noscript>				
		<script defer="defer">
			if (navigator.cookieEnabled === false) {
				document.location.href='main/nocookies.html?returnto=<?php echo urlencode((string) Ajde::app()->getRoute()); ?>';
			}
		</script>
		
		<!-- Make IE6-8 HTML5 compliant, somewhat... -->
		<!--[if lt IE 9]>
		<script src='public/js/lib/html5shiv.js'></script>
		<![endif]-->
		
		<!-- Favicon and CSS -->
		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		<?php echo $this->getDocument()->getHead('css'); ?>
		
	</head>
	
	<!-- Target older versions of IE with CSS classes -->
	<!--[if lt IE 7 ]> <body class='ie6 oldie'> <![endif]-->
	<!--[if IE 7 ]>    <body class='ie7 oldie'> <![endif]-->
	<!--[if IE 8 ]>    <body class='ie8 oldie'> <![endif]-->
	<!--[if IE 9 ]>    <body class='ie9'> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container-fluid">
					<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
					</button>
					<a class="brand" href="admin"><?php echo Config::get('sitename'); ?></a>
					<div class="nav-collapse collapse">
						<?php if ($user) { ?>
							<ul class="nav pull-right">
								<li class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" href="user">
                                        <?php echo Ajde_Resource_Image_Gravatar::get($user->getEmail(), 18, 'identicon', 'g', true); ?> &nbsp;
                                        <?php echo $user->getUsername(); ?> <b class="caret"></b>
                                    </a>
									<ul class="dropdown-menu">
										<li><a href="user">Profile</a></li>
										<li><a href="user/settings">Settings</a></li>
										<li><a href="user/app">App</a></li>
										<li class="divider"></li>
										<li><a href="user/logoff">Log out</a></li>
									</ul>
								</li>
							</ul>						
							<form class="navbar-search pull-right">
								<input type="text" name="q" id="node-search" placeholder="Search nodes">
								<div id="node-search-results"></div> 
							</form>
						<?php } else { ?>
							<ul class="nav pull-right">
								<li><a href="user/logon">Login</a></li>
							</ul>	
						<?php } ?>
						
						<ul class="nav">
							<?php if ($user) { ?>
								<!-- <li><a href="admin">Dashboard</a></li> -->
								<li class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" href="admin/cms:nodes">Content <b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li class="nav-header">Nodes</li>
										<li><a href="admin/node:view?view[filter][nodetype]=&nofilterpopup=1">Overview</a></li>
										<?php foreach ($nodeTypes as $nodeType) {  
											/* @var $nodeType NodetypeModel */
											if ($nodeType->get('category') <> $currentGrouper) {
												if (!empty($currentGrouper)) { echo '</ul>'; }
												$currentGrouper = $nodeType->get('category'); ?>
												<li class="with-sub-menu">
													<a href="javascript:void(null);">
														<?php echo ucfirst($currentGrouper); ?> <i class="icon-chevron-right pull-right"></i>
													</a>
													<ul class="dropdown-menu sub-menu">
											<?php } ?>
											<li><a href="admin/node:view?view[filter][nodetype]=<?php echo $nodeType->getPK(); ?>"><?php echo _e($nodeType->getName()); ?></a></li>
										<?php }
										if ($nodeTypes->count() && !empty($currentGrouper)) { ?>
											</ul>
										</li>
										<?php } ?>
										<li class="divider"></li>
										<li><a href="admin/media:view">Media</a></li>
										<li><a href="admin/menu:view">Menus</a></li>
										<li><a href="admin/tag:view">Tags</a></li>
									</ul>
								</li>
								<li><a href="admin/cms:settings">Settings</a></li>
							<?php }
							if ($user && (string) $user->getUsergroup() == UserModel::USERGROUP_ADMINS) { ?>
								<li class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" href="admin/setup:nodes">Setup <b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li class="nav-header">Meta setup</li>
										<li><a href="admin/setup:nodes">Nodes</a></li>
										<li><a href="admin/setup:media">Media</a></li>
										<li><a href="admin/setup:menus">Menus</a></li>
										<li><a href="admin/setup:settings">Settings</a></li>
										<li><a href="admin/setup:meta">Meta fields</a></li>
										<li class="nav-header">Access</li>
										<li><a href="admin/user:view">Users</a></li>
										<li><a href="admin/acl:view">Pages &amp; models</a></li>	
										<li class="nav-header">Maintenance</li>
										<li><a href="admin/system:check">System check</a></li>
										<li><a href="admin/system:update">Update</a></li>
									</ul>
								</li>
							<?php } ?>
							<li><a href="./">View site</a></li>
						</ul>
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>

		<div class="container-fluid">
		
			<div id="no-chrome-warning" class="chrome alert menu-offset">
				<img src="https://lh3.ggpht.com/7O3H3V0fEBumwJlqDLD03t1fmwl8fH9YoBsPwB2UQ_aiBilM7OAOe2gkFB3wrojJqbM=w50" class="pull-left" alt="Chrome logo" />
				<p>
					The website you're managing is optimized for all regular browsers. This administration section however, works best with Google Chrome.<br/>
					<i class="icon-chevron-right icon-white"></i><a href="http://chrome.google.com">Please  download &amp; install Google Chrome</a>
				</p>
			</div>
			
			<?php echo $this->getDocument()->getBody(); ?>
			
			<div class="clearfix"></div>
			
			<hr>
			
			<?php
			$chromeapp = new Ajde_Session('env');
			if (Ajde::app()->getRequest()->getInt('chromeapp', false) === 1) {
				$chromeapp->set('chromeapp', 1);
			}
			if (!$chromeapp->has('chromeapp')) { ?>
			<div id="chrome-app" class="chrome well menu-offset">
				<img src="https://lh3.ggpht.com/7O3H3V0fEBumwJlqDLD03t1fmwl8fH9YoBsPwB2UQ_aiBilM7OAOe2gkFB3wrojJqbM=w50" class="pull-left" alt="Chrome logo" />
				<p>
					There's a Chrome app available for easy access to this administration panel.<br/>
					<i class="icon-chevron-right"></i><a href="admin/system:chromeApp">Install now</a>
				</p>
			</div>
			<?php } ?>
			
			<footer class="menu-offset">
				<span class="pull-right ajde-footer">
					Powered by <a href="https://github.com/hongaar/ajde"><img src="<?php echo MEDIA_DIR; ?>ajde-small.png" /></a> web administration platform				
				</span>
				<p>&copy; <?php echo date('Y'); ?> <?php echo Config::get('author'); ?></p>
			</footer>

		</div><!--/.fluid-container-->
		
		<div id="loading">
			<div>
				<div class="spinner"><strong>loading...</strong><span></span></div>
			</div>
		</div>
		
		<!-- The scripts -->
		<?php echo $this->getDocument()->getScripts(); ?>
		
		<!-- Google Analytics -->
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-XXXXX-X']);
			_gaq.push(['_trackPageview']);
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
		
		<!-- updatemybrowser.org widget -->
		<script type="text/javascript">
		(function() {
			var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true;
			s.src = ('https:'==document.location.protocol?'https://':'http://') + 'updatemybrowser.org/umb.js';
			var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(s, b);
		})();	
		</script>
		
	</body>
</html>

<!-- Some debugging info -->
<!--[<pre>
	<?php $version = Config::get('version'); echo Config::get('ident') . ', v' . $version['number'] . ' (' . $version['name'] . ')'; ?> 
	Cache <?php echo Ajde_Cache::getInstance()->isEnabled() ? 'enabled' : 'disabled' ?> 
	Last modified on <?php echo date("r", Ajde_Cache::getInstance()->getLastModified()); ?> 
</pre><![-->