<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="row-fluid">
    <div class="span2">
        <?php echo $this->includeModule('admin/cms:setupmenu'); ?>
    </div><!--/span-->
    <div class="span10">
		<div class="page-header">
			<h1>
				<?php echo esc(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>


        <div class="row-fluid">

            <div class="span12">

                <h2>All systems go?</h2>
                <?php foreach($this->results as $result) { ?>
                    <div>
                        <span class="label label-<?php echo $result['status']; ?>">
                            <?php echo esc($result['check']); ?>
                        </span>
                        <span class="pull-right">
                            <?php echo esc($result['msg']); ?>
                        </span>
                    </div>
                <?php } ?>

                <h2>Configuration</h2>

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Key</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->config as $k => $v) { ?>
                            <tr>
                                <td>
                                    <?php echo esc($k); ?>
                                </td>
                                <td>
                                    <?php if (is_array($v)) { ?>
                                        <?php echo esc(json_encode($v)); ?>
                                    <?php } else { ?>
                                        <?php echo esc($v); ?>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>

        </div><!--/row-->
    </div>
</div>
