<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

// Fancybox
$this->requireJsPublic('core/fancybox/jquery.fancybox.pack.js');
$this->requireCssPublic('core/fancybox/jquery.fancybox.css');

// Fancybox thumb helper
$this->requireJsPublic('core/fancybox/helpers/jquery.fancybox-thumbs.js');
$this->requireCssPublic('core/fancybox/helpers/jquery.fancybox-thumbs.css');

// Lazyload
$this->requireJsPublic('core/jquery.lazyload.min.js');

/* @var $field Ajde_Crud_Field_File */
$field = $this->field;

?>

<div class='fileupload <?php if ($field->getValue()) { echo 'hidden'; } ?>'>

	<?php
	$options = array(
		'saveDir' => $field->getSaveDir(),
		'extensions' => $field->getExtensions(),
		'multiple' => $field->getMultiple(),
		'overwrite' => $field->getOverwrite()
	);
	echo $this->ACAjaxUpload($field->getName(), $options); ?>

	<div class='filebrowser'>
		<span class="filebrowser-control">or &nbsp; <a href='javascript:void(0);' class='btn search toggleFileBrowser'><i class="icon-search"></i> <?php echo esc('choose existing'); ?></a></span>
        <div class='browser'>
            <input class="span12 search" type="search" placeholder="search"/>
			<?php
			$filelist = Ajde_Fs_Find::findFiles($field->getSaveDir(), "{*." . implode(',*.', Ajde_Fs_Find::mkglobi($field->getExtensions())) . "}", GLOB_BRACE);
			$exclude = preg_grep("/_[0-9]+x[0-9]+c?/i", $filelist);
			foreach($filelist as $file) {
				if (in_array($file, $exclude)) {
					continue;
				}
				$extension = pathinfo($file, PATHINFO_EXTENSION);
				echo "<a href='javascript:void(0);' title='" . esc(str_replace(LOCAL_ROOT . DIRECTORY_SEPARATOR . $field->getSaveDir(), '', $file)) . "'>";
					if ($isImage = in_array(strtolower($extension), array('jpg', 'jpeg', 'png', 'gif'))) {
						// Don't use $this->ACImage() to support lazy loading
						$image = new Ajde_Resource_Image(str_replace(LOCAL_ROOT, '', $file));
						$image->setWidth(50);
						$image->setHeight(50);
						$image->setCrop(true);
						echo "<img class='thumb' data-original='" . $image->getLinkUrl() . "' src='" . MEDIA_DIR . "gray.gif' width='50' height='50' />";

					} else {
						echo "<span class='icon'><img class='icon' src='" . Ajde_Resource_FileIcon::_($extension) . "' /></span>";
					}
					echo "<span>";
						echo "<span class='filename'>" . str_replace(LOCAL_ROOT . $field->getSaveDir(), '', $file) . "</span>";
						if ($isImage) {
							echo "<span class='imagePreview preview' data-fancybox-group='preview" . ucfirst($field->getName()) . "' title='" . esc(str_replace(LOCAL_ROOT . $field->getSaveDir(), '', $file)) . "' href='" . $this->escape(str_replace(LOCAL_ROOT, '', $file)) . "'>preview</span>";
						} else {
							echo "<span class='filePreview preview' href='" . $this->escape(str_replace(LOCAL_ROOT . DIRECTORY_SEPARATOR, '', $file)) . "'>preview</span>";
						}
					echo "</span>";
				echo "</a>";
			}
			?>
			<div class='clearfix'></div>
		</div>
	</div>

</div>

<?php

if ($field->getValue()) {
	$extension = pathinfo($field->getValue(), PATHINFO_EXTENSION); ?>

	<div class='filelist'>

		<input
			<?php echo $field->getHtmlAttributes(); ?>
		/>

		<?php
		if ($isImage = in_array(strtolower($extension), array('jpg', 'jpeg', 'png', 'gif'))) {
			$thumbDim = $field->hasThumbDim() ? $field->getThumbDim() : array('width' => 150, 'height' => 150); ?>
			<a class='imagePreview img' title='<?php echo esc($field->getValue()); ?>' href='<?php echo $field->getSaveDir() . $field->getValue(); ?>' target='_blank'>
				<?php echo $this->ACImage(array(
						'filename' => $field->getSaveDir() . $field->getValue(),
						'width' => $thumbDim['width'],
						'height' => $thumbDim['height'],
						'crop' => true
					)); ?>
			</a>
		<?php } ?>

		<span>
			<?php if ($isImage) { ?>
				<a class='imagePreview preview btn' title='<?php echo esc($field->getValue()); ?>' href='<?php echo $field->getSaveDir() . $field->getValue(); ?>' target='_blank'>
                    <img class='icon' src='<?php echo Ajde_Resource_FileIcon::_($extension); ?> ' />
                    <?php echo $field->getValue(); ?>
                </a>
			<?php } else { ?>
				<a class='filePreview preview btn' href='<?php echo $field->getSaveDir() . $field->getValue(); ?>' target='_blank'>
                    <?php echo $field->getValue(); ?>
                </a>
			<?php } ?>
			<a href='#' class='deleteFileCrud btn btn-danger'>delete</a>
		</span>

	</div>

<?php } ?>
