<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */

$options = new Ajde_Crud_Options();
$options	
	->selectFields()
		->selectField('name')
			->up()
		->selectField('lang')
            ->setFunction('displayLang')
            ->setType('i18n')
            ->setCloneFields(array(
                'name', 'master', 'style', 'subject', 'content'
            ))
			->up()
		->selectField('subject')
            ->setEmphasis(true)
			->up()
        ->selectField('content')
			->up()
        ->selectField('master')
            ->up()
		->up()
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->up()
		->setMain('subject')
		->setShow(array('name', 'subject', 'lang'))
		->selectView()
			->setOrderBy('name')
			->up()
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(8)
					->addBlock()
                        ->setClass('sidebar')
						->setShow(array('name'))
						->up()
                    ->addBlock()
                        ->setClass('primary narrow sidebar')
                        ->setShow(array('subject'))
                        ->up()
                    ->addBlock()
                        ->setClass('sidebar')
                        ->setShow(array('content'))
                        ->up()
					->up()
				->addColumn()
					->setSpan(4)
                    ->addBlock()
                        ->setTitle('Style')
                        ->setClass('well')
                        ->setShow(array('master', 'style'))
                        ->up()
                    ->addBlock()
						->setTitle('Metadata')
						->setClass('well')
						->setShow(array('lang'))
						->up()		
									
		
	->finished();

$crud = $this->ACCrudList('template', $options);

?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/cms:menu'); ?>		
	</div><!--/span-->
	<div class="span10 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>

        <?php if (!Ajde::app()->getRequest()->has('edit') && !Ajde::app()->getRequest()->has('new')) {
            echo $this->includeModule('admin/email:menu');
        } ?>
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->