<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */

$options = new Ajde_Crud_Options();
$options
	->selectFields()
		->selectField('title')
			->setEmphasis(true)
			->up()
		->selectField('image')
			->setType('file')
			->setSaveDir(MEDIA_DIR . ProductModel::$imageDir)
			->setExtensions(array('png', 'jpg', 'pdf', 'docx'))
			->setMultiple(false)
			->setLabel('Plaatje')
			->setLength(255)
			->setIsRequired(false)
			->setDefault('')
			->setIsAutoIncrement(false)
			->setThumbDim(266, 100)
			->up()
		->selectField('published')
			->setType('boolean')
			->up()
		->selectField('sort')
			->setType('sort')
			->up()
        ->selectField('stock')
			->setLabel('Stock')
			->up()
		->selectField('unitprice')
			->setHelp('Sets the unit price')
			->up()
		->selectField('slug')
			->setIsReadonly(true)
            ->setLabel('Slug')
			->up()
        ->selectField('updated')
            ->setLabel('Updated on')
            ->up()
		->selectField('encrypted_field')
			->setDisableRichText(true)
			->setTextInputHeight(4)
			->up()
		->up()
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
            ->setView(true)
            ->setViewUrlFunction('getSlug')
			->up()
		->setMain('title')
		->setShow(array('title', 'image', 'unitprice', 'vat', 'stock', 'published', 'sort', 'updated'))
		->selectView()
			->setOrderBy('sort')
			->up()
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(8)
					->addBlock()
						->setShow(array('title', 'content'))
						->up()
					->addBlock()
						->setTitle('Pricing')
						->setClass('')
						->setShow(array('unitprice', 'vat'))
						->up()
					->up()
				->addColumn()
                    ->setSpan(4)
					->addBlock()
						->setTitle('Media')
						->setClass('sidebar')
						->setShow(array('image'))
						->up()
					->addBlock()
						->setTitle('Metadata')
						->setClass('well')
						->setShow(array('updated', 'stock', 'published', 'slug', 'user'))
						->up()

	->finished();

$crud = $this->ACCrudList('product', $options);

if (Ajde::app()->getRequest()->has('new')) {
    $user = UserModel::getLoggedIn();
    $crud->setOption('fields.user.value', $user->getPK());
}

?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/shop:menu'); ?>
	</div><!--/span-->
	<div class="span10 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>		
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->