<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */

$options = AdminShopController::getTransactionOptions();
$crud = $this->ACCrudList('transaction', $options);

?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/shop:menu'); ?>
	</div><!--/span-->
	<div class="span10 expandInIframe">

		<div class="page-header">
			<h1>
				<?php echo esc(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>

		<?php echo $crud->output(); ?>

	</div><!--/span-->
</div><!--/row-->
