<div class="row-fluid">
	<div class="span6">
	
		<fieldset>
			<legend><?php echo $this->clean($this->message); ?></legend>
			
			
			<p>
				Already logged on.
			</p>
			
			<p>
				<a class='btn btn-primary' href="user/logoff?returnto=<?php echo isset($this->returnto) ? $this->returnto : Ajde::app()->getRoute(); ?>"><?php echo __('Login as a different user'); ?></a>
			</p>
		</fieldset>
	
	</div><!--/span-->
</div>