<?php $field = $this->field; ?>

<input
	<?php echo $field->getHtmlAttributes(); ?>
/>

<fieldset class='picker-container'>

	<input
		type='checkbox'
		class='autoUpdateCrud'
		<?php
		if ($field->getValue()) echo 'checked="checked"';
		if ($this->id) { echo 'id="' . $this->id . '"'; } else { echo 'id="check_' . $field->getName() . '"'; }
		if ($field->hasReadonly() && $field->getReadonly() === true) {
			echo ' disabled="disabled" ';	
		}
		?>
	/>
	<label class="radio" for="<?php if ($this->id) { echo $this->id; } else { echo 'check_' . $field->getName(); } ?>">
		<?php if ($field->getValue()) { echo 'On'; } else { echo 'Off'; } ?>
	</label>

</fieldset>