<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

/* @var $field Ajde_Crud_Field */
$field = $this->field;
?>

<input
	<?php echo $field->getHtmlAttributes(); ?>
/>

<?php

if ($field->hasUseImage() && $field->getUseImage()) {
   
    if (!$field->hasLayerImage()) {
        throw new Ajde_Exception('Please set layerImage for this model in afterCrudLoaded hook');
    }
    
    ?>
    <div class="spatial image">
    <?php    
        echo $this->ACImage(array(
            'filename' => $field->getLayerImage(),
            'width' => 800,
            'class' => 'spatial'
        ));
    ?>
        <div class="spatialMarker"></div>
    </div>
    <?php
    
} else {
    
    $apiKey = Config::get('apiKeys');
    $apiKey = $apiKey['google'];

    $this->requireJsRemote('https://maps.googleapis.com/maps/api/js?key=' . $apiKey . '&sensor=false');

    ?>

    <div class="spatial gmaps"></div>
    
<?php } ?>