<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$this->requireJsPublic('core/jqtree/tree.jquery.js');
$this->requireCssPublic('core/jqtree/jqtree.css');

?>

<div class="well sidebar-nav">
	<a class="menu-toggle btn btn-normal pull-right"><i class="icon-resize-small"></i></a>
	<p class="controls">
		<a class="btn-primary btn" href="admin/node:view">Overview</a>
		<a class="btn refresh-nav"><i class="icon-refresh"></i></a>
	</p>
	<div id="nav-tree">
		Loading nodes...
	</div>
</div><!--/.well -->