<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$this->requireJsPublic('core/jqtree/tree.jquery.js');
$this->requireCssPublic('core/jqtree/jqtree.css');

?>

<div class="well sidebar-nav">
	<a class="menu-toggle btn btn-normal pull-right"><i class="icon-resize-small"></i></a>
	<div class="btn-group">
		<a class="btn-primary btn" href="admin/node:view"><i class="icon-white icon-list"></i></a>
		<a class="btn refresh-nav"><i class="icon-refresh"></i></a>
	</div>
	<div id="nav-tree">
		Loading nodes...
	</div>
    <hr/>
    <?php include '_menu.phtml'; ?>
</div><!--/.well -->