<div class="well sidebar-nav">
	<a class="menu-toggle btn btn-normal pull-right"><i class="icon-resize-small"></i></a>
	<ul class="nav nav-list">
        <li class="nav-header">Meta setup</li>
        <li><a href="admin/setup:nodes">Nodes</a></li>
        <li><a href="admin/setup:media">Media</a></li>
        <li><a href="admin/setup:menus">Menus</a></li>
        <li><a href="admin/setup:settings">Settings</a></li>
        <li class="divider"></li>
        <li><a href="admin/setup:meta">Meta fields</a></li>
        <li class="nav-header">Access</li>
        <li><a href="admin/user:view">Users</a></li>
        <li><a href="admin/acl:view">Pages &amp; models</a></li>
        <li class="nav-header">Maintenance</li>
        <li><a href="admin/system:cleanuploads">Clean uploads</a></li>
        <li><a href="admin/system:check">System check</a></li>
        <li><a href="admin/system:update">Update</a></li>
        <li><a href="admin/system:log">Log</a></li>
	</ul>
</div><!--/.well -->