<div class="well sidebar-nav">
	<a class="menu-toggle btn btn-normal pull-right"><i class="icon-resize-small"></i></a>
	<ul class="nav nav-list">
		<li class="nav-header">Setup</li>
		<li><a href="admin/setup:nodes">Nodes</a></li>
        <li><a href="admin/setup:media">Media</a></li>
		<li><a href="admin/setup:menus">Menus</a></li>        
		<li><a href="admin/setup:settings">Settings</a></li>
		<li class="divider"></li>
		<li><a href="admin/setup:meta">Meta fields</a></li>
	</ul>
</div><!--/.well -->