<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

?>

<div class="row-fluid">
	<div class="span12 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo Ajde::app()->getDocument()->getTitle(); ?>
			</h1>
		</div>		
		
		<div class="row-fluid">
			<div class="span8 offset2">
				
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>Streak</th>
							<th>Total time</th>
							<th>Total cost</th>
						</tr>
					</thead>
					<tbody>
						<?php if (count($this->streaks) == 0) { ?>
							<tr>
								<td colspan="3">No billable streaks</td>
							</tr>
						<?php } ?>
						<?php foreach($this->streaks as $streak) {
							/* @var $streak NodeModel */ ?>
							<tr>
								<td><a href="issue/view?parent=<?php echo $streak->getPK(); ?>"><?php echo $streak->displayRootName(); ?></a></td>
								<td><?php echo NodeModel::span2str($streak->getTotalTime()); ?></td>
								<td>€ <?php echo $streak->getTotalCost(); ?></td>
							</tr>
						<?php } ?>
					</tbody>
				</table>
				
			</div><!--/span-->
		</div>
		
	</div><!--/span-->
</div><!--/row-->