<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */

/* @var $user UserModel */
$user = $this->user; 
$auth = $user->getPK() . ':' . $user->getCookieHash(false);

?>

<div class="container">
    <div class="row-fluid">
        <?php echo $this->includeModule('user/menu'); ?>
        <div class="span9 col-sm-9">

            <div class='page-header'>
                <?php echo $this->user->displayGravatar(90, 'pull-left'); ?> &nbsp;
                <h1> &nbsp; App</h1>
            </div>

            <div class="row-fluid">
                <div class="span6 col-sm-6">
                    <h2>Download our Android app</h2>
                    <a href="javascript:alert('No known app for this project');">
                        <img alt="Get it on Google Play"
                            src="https://developer.android.com/images/brand/en_generic_rgb_wo_60.png" />
                    </a>
                </div>
                <div class="span6 col-sm-6">
                    <h2>Authenticate your app</h2>
                    <input type="text" readonly value="<?php echo $auth; ?>" class="span12" />
                    <p><?php echo $this->ACQrcode(array('text' => $auth)); ?></p>
                </div>
            </dl>
        </div>
    </div>
</div>

