<div class="span3 col-sm-3">
    <div class="well sidebar-nav">
        <a class="menu-toggle btn btn-normal pull-right"><i class="icon-resize-small"></i></a>
        <ul class="nav nav-list">
            <li class="nav-header">User account</li>
            <li><a href="user/profile"><i class="icon-user"></i> Profile</a></li>
            <li><a href="user/social"><i class="icon-thumbs-up"></i> Social</a></li>
            <li><a href="user/settings"><i class="icon-cog"></i> Settings</a></li>
            <li><a href="user/app"><i class="icon-qrcode"></i> App</a></li>
            <li class="divider"></li>
            <li><a href="user/logoff"><i class="icon-share-alt"></i> Log off</a></li>
        </ul>
    </div><!--/.well -->
</div><!--/span-->