<div class="row-fluid">
	<div class="span12">

		<fieldset>
			<legend><?php echo $this->message ? $this->clean($this->message) : 'No need to logon again'; ?></legend>

			<p>
				You are already logged on.
			</p>

			<?php if (config("app.debug") === true) {
				echo '<div class="well"><span class="badge badge-important">ACL debug</span><p>';
				foreach(Ajde_Acl::$log as $log) {
		            echo $log . '<br/>';
		        }
				echo '</p></div>';
			} ?>

			<p>
				<?php // Use $_GET['_route'] to avoid getting the current route, i.e. as with Ajde::app()->getRoute() ?>
				<a class='btn btn-primary' href="user/logoff?returnto=<?php echo isset($this->returnto) ? $this->returnto : issetor($_GET['_route']); ?>"><?php echo __('login as a different user'); ?></a>
				<a class='btn' href="user/profile"><?php echo __('view profile'); ?></a>
			</p>
		</fieldset>

	</div><!--/span-->
</div>
