<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="row-fluid">
	<div class="span2">
		<?php echo $this->includeModule('admin/cms:menu'); ?>		
	</div><!--/span-->
	<div class="span10">
		
		<div class="page-header">
			<h1><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></h1>
		</div>
		
		<p class="lead">
			Media are files and embeds.
		</p>
		<p>
			<a href="admin/media:view" class="btn btn-primary btn-large">media manager &raquo;</a>
            <a href="admin/media:view?new" class="btn btn-primary btn-large">new media &raquo;</a>
			<a href="admin/media:upload" class="btn btn-primary btn-large">upload multiple files &raquo;</a>
		</p>
		
	</div><!--/span-->
</div><!--/row-->