<div class="well sidebar-nav">
	<ul class="nav nav-list">
		<li class="nav-header">Nodes</li>
		<li><a href="admin/node:view"><i class="icon-list"></i> Node overview</a></li>
		<li><a href="admin/node:new"><i class="icon-plus"></i> Create new node</a></li>
		<li class="nav-header">Media</li>
		<li><a href="#"><i class="icon-th-large"></i> Media manager</a></li>
		<li><a href="#"><i class="icon-circle-arrow-up"></i> Upload new media file</a></li>
		<li class="nav-header">Menus</li>
		<li><a href="#"><i class="icon-bookmark"></i> Add/remove items from a menu</a></li>
	</ul>
</div><!--/.well -->