<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="row-fluid">
	<div class="span2">
		<?php echo $this->includeModule('admin/cms:menu'); ?>		
	</div><!--/span-->
	<div class="span10">
		
		<div class="page-header">
			<h1><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></h1>
		</div>
		
		<p class="lead">
			Tags are just tags
		</p>
		<p>
			<a href="admin/tag:view" class="btn btn-primary btn-large">tag overview &raquo;</a>
			<a href="admin/tag:view?new" class="btn btn-primary btn-large">add tag &raquo;</a>
		</p>
		
	</div><!--/span-->
</div><!--/row-->