<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$updater = $this->updater;
/* @var $updater Ajde_Core_Updater */ 
?>

<div class="row-fluid">
	<div class="span12">		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>			
	</div>
</div>

<div class="row-fluid">
	
	<div class="span12">		
			
		<p>
			Current version: <?php echo $updater->getCurrentVersion(); ?><br/>
			Available version: <?php echo $updater->getAvailableVersion(); ?>
		</p>
		
		<?php if ($updater->isUpdateable()) { ?>
		
			<a href="admin/system:update?do" class="btn btn-success btn-large">Update now</a>
		
		<?php } ?>
			
	</div>		
	
</div><!--/row-->