<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="container">

    <div class="row row-fluid">
        <div class="span12 col-md-12">
            <div class="page-header">
                <h1><?php echo trans("We've taken a security measure"); ?></h1>
            </div>
        </div>
    </div>

    <div class="row row-fluid">
        <div class="span8 col-md-12 col-lg-4">
            <p>
                <?php echo trans('You may have looked this page up some time, or from another location or device, and it has expired.'); ?>
            </p>
            <a class='action btn btn-primary' href='javascript:void(0);' onclick='window.location.reload(true);'>
                <?php echo trans("Reload this page"); ?>
            </a>
        </div>
        <div class="span4 col-md-12 col-lg-6 col-lg-offset-2 col-offset-2">
            <img src="assets/media/404.png" class="img-responsive" />
        </div>
    </div>

</div>
