<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */

$options = new Ajde_Crud_Options();
$options
	->selectFields()
		->selectField('name')
			->setEmphasis(true)
			->up()
		->selectField('sort')
			->setType('sort')
			->up()
		->up()
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->up()
		->setMain('name')
		->setShow(array('name', 'sort'))
		->selectView()
			->setOrderBy('sort')
			->up()
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(8)
					->addBlock()
						->setShow(array('name'))

	->finished();

$crud = $this->ACCrudList('tag', $options);

?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/cms:menu'); ?>
	</div><!--/span-->
	<div class="span10 expandInIframe">

		<div class="page-header">
			<h1>
				<?php echo esc(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>

		<?php echo $crud->output(); ?>

	</div><!--/span-->
</div><!--/row-->
