<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
/* @var $node NodeModel */

$node = $this->node;
?>

<div class="container main">

	<div class="row">
		<div class="col-sm-12">
            <h1><?php echo esc(Ajde::app()->getDocument()->getTitle()); ?></h1>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-6">
			<?php echo clean($node->content); ?>

			<p>
				<?php foreach($node->getChildren() as $child) {
					/* @var $child NodeModel */ ?>
					<a class='btn btn-default' href='<?php echo esc($child->getUrl())?>'>
						<?php echo esc($child->getTitle()); ?>
					</a>
				<?php } ?>
			</p>

            <?php if ($formId = $node->getMetaValue('form')) {
                echo $this->ACEmbedForm($formId);
            } ?>
		</div>
		<div class="col-sm-6">
            <?php if (($media = $node->getMedia()) && $media->hasLoaded()) { ?>
                <figure>
                    <?php echo $media->getLazyTag(800, null, null, 'img-responsive'); ?>
                    <?php if ($media->caption) { echo clean($media->caption); } ?>
                </figure>
            <?php } ?>

            <?php foreach($node->getAdditionalMedia() as $media) {
                /* @var $media MediaModel */ ?>
                <?php if ($media->getType() == 'embed')
                {
                    $embed = Ajde_Embed::fromCode($media->getPointer());
                    $embed->setHeight('10px');
                    $embed->setWidth('100%');

                    echo "<div class='embed'>";
                    echo $embed->getCode();
                    echo "</div>";
                } else { ?>
                    <figure>
                        <?php echo $media->getLazyTag(800, null, null, 'img-responsive'); ?>
                        <?php if ($media->caption) { echo clean($media->caption); } ?>
                    </figure>
                <?php } ?>
            <?php } ?>
		</div>
	</div>

</div>
