<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo config("app.id"); ?>'>
	<head>
		<meta charset='utf-8'>
		<title><?php echo esc(strip_tags(Ajde::app()->getDocument()->getFullTitle())); ?></title>
		<?php echo Ajde::app()->getDocument()->getHead('css'); ?>
	</head>
    <body>
		<div id='wrapper'>
			<?php echo Ajde::app()->getDocument()->getBody(); ?>
		</div>
		<?php echo Ajde::app()->getDocument()->getScripts(); ?>
	</body>
</html>
