<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

// ============== STYLES

// Default style
$this->requireCss('default');
$this->requireCssPublic('core/bootstrap/bootstrap-cosmo.css', Ajde_Document_Format_Html::RESOURCE_POSITION_FIRST);
$this->requireGWebFont('Roboto', array(300, 500, 700));

// =====================

// Twitter bootstrap
$this->requireCssPublic('core/bootstrap/bootstrap-responsive.css', Ajde_Document_Format_Html::RESOURCE_POSITION_FIRST);
$this->requireCss('bootstrap');

// Include jQuery 1.7
$this->requireJsLibrary('jquery', '1.8');

// Fastclick
$this->requireJsPublic('core/fastclick.js');

// Bootstrap.js
$this->requireJsPublic('core/bootstrap/bootstrap.min.js');

// jqBootstrapValidation.js
$this->requireJsPublic('core/jqBootstrapValidation.js');

// jQuery cookie
$this->requireJsPublic('core/jquery.cookie.js');

// Chosen
$this->requireJsPublic('core/chosen/chosen.jquery.min.js');
$this->requireCssPublic('core/chosen/chosen.css');
$this->requireCss('chosen');

// Picker
$this->requireJsPublic('core/picker/jquery.fs.picker.min.js');
$this->requireCssPublic('core/picker/jquery.fs.picker.css');
$this->requireCss('picker');

// CKEditor
$this->requireCss('ckeditor');

// Some JavaScript i18n
$this->requireJsFirst('i18n.' . Ajde_Lang::getInstance()->getShortLang());

// Alert bar
$this->requireJsFirst('core.alert');
$this->requireCssFirst('core.alert');

// Additional CSS
$this->requireCss('default.crud');

?>
<!-- Inspired by HTML5 Boilerplate -->
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo Config::get('ident'); ?>' data-lifetime='<?php echo (Config::get('sessionLifetime') == 0 ? 180 : Config::get('sessionLifetime')); ?>' data-alert='<?php echo _e(Ajde_Session_Flash::get('alert')); ?>'>
	<head>
		
		<!-- UTF-8 please (also in the headers, just to be sure) -->
		<meta charset='utf-8'>
		
		<!-- Some content meta tags -->
		<title><?php echo _e(strip_tags(Ajde::app()->getDocument()->getFullTitle())); ?></title>		
		
		<!-- Define the root of the site -->
		<base href='<?php echo Config::get('lang_root'); ?>' />
		
		<!-- Favicon and CSS -->
		<?php echo $this->getDocument()->getHead('css'); ?>
		
	</head>
	
	<!-- Target older versions of IE with CSS classes -->
	<!--[if lt IE 7 ]> <body class='ie6 oldie'> <![endif]-->
	<!--[if IE 7 ]>    <body class='ie7 oldie'> <![endif]-->
	<!--[if IE 8 ]>    <body class='ie8 oldie'> <![endif]-->
	<!--[if IE 9 ]>    <body class='ie9'> <![endif]-->
	<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->
		
		<!-- The content -->		
		<div class='container'>
			<div class='row'>							
				<div class='twelvecol'>
					<?php echo $this->getDocument()->getBody(); ?>
				</div>
			</div>
		</div>

		<!-- The scripts -->
		<?php echo $this->getDocument()->getScripts(); ?>

        <!-- Google Analytics -->
        <script>
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-XXXXX-X']);
            _gaq.push(['_trackPageview']);
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>

        <!-- updatemybrowser.org widget -->
        <script>
            (function() {
                var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true;
                s.src = '//updatemybrowser.org/umb.js';
                var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(s, b);
            })();
        </script>
				
	</body>
</html>

<!-- Some debugging info -->
<!--[<pre>
	<?php $version = Config::get('version'); echo Config::get('ident') . ', v' . $version['number'] . ' (' . $version['name'] . ')'; ?> 
	Cache <?php echo Ajde_Cache::getInstance()->isEnabled() ? 'enabled' : 'disabled' ?> 
	Last modified on <?php echo date("r", Ajde_Cache::getInstance()->getLastModified()); ?> 
</pre><![-->
