<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */

// ============== STYLES

// Bootstrap theme
$this->requireCssPublic('core/bootstrap/bootstrap-cosmo.css', Ajde_Document_Format_Html::RESOURCE_POSITION_FIRST);
$this->requireGWebFont('Roboto', array(300, 500, 700));

// Bootstrap overrides
$this->requireCss('bootstrap');
$this->requireCss('yellow');

// Shortcut
$this->requireCss('core.shortcut');
$this->requireJs('core.shortcut');

// =====================

// Include jQuery 1.8
$this->requireJsLibrary('jquery', '1.8');

// Fastclick
$this->requireJsPublic('core/fastclick.js');

// Autocomplete
$this->requireJsPublic('core/jquery.autocomplete.min.js');

// Bootstrap.js
$this->requireJsPublic('core/bootstrap/bootstrap.min.js');

// jqBootstrapValidation.js
$this->requireJsPublic('core/jqBootstrapValidation.js');

// jQuery cookie
$this->requireJsPublic('core/jquery.cookie.js');

// Chosen
$this->requireJsPublic('core/chosen/chosen.jquery.min.js');
$this->requireCssPublic('core/chosen/chosen.min.css');
$this->requireCss('chosen');

// Selectize
$this->requireJsPublic('core/jqueryui/sortable/jquery-ui.min.js');
$this->requireJsPublic('core/selectize/selectize.min.js');
$this->requireCssPublic('core/selectize/selectize.css');
$this->requireCss('selectize');

// Picker
$this->requireJsPublic('core/picker/jquery.fs.picker.min.js');
$this->requireCssPublic('core/picker/jquery.fs.picker.css');
$this->requireCss('picker');

// CKEditor
$this->requireCss('ckeditor');

// JavaScript i18n
$this->requireJsFirst('i18n.' . Ajde_Lang::getInstance()->getShortLang());

// Alert bar
$this->requireJsFirst('core.alert');
$this->requireCssFirst('core.alert');

// Additional CSS
$this->requireCss('default.crud');
$this->requireCss('default.tablet', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="only screen and (max-width: 979px)"');
$this->requireCss('default.phone', 'html', null, Ajde_Document_Format_Html::RESOURCE_POSITION_LAST, 'media="only screen and (max-width: 767px)"');

// The user
$user = UserModel::getLoggedIn();

?>
<!-- Inspired by HTML5 Boilerplate -->
<!doctype html>
<html lang='<?php echo Ajde_Lang::getInstance()->getShortLang(); ?>' id='<?php echo config("app.id"); ?>' data-lifetime='<?php echo (config("session.lifetime") == 0 ? 180 : config("session.lifetime")); ?>' data-alert='<?php echo esc(Ajde_Session_Flash::get('alert')); ?>'>
	<head>

		<!-- UTF-8 please (also in the headers, just to be sure) -->
		<meta charset='utf-8'>

		<!-- Some content meta tags -->
		<title><?php echo esc(strip_tags(Ajde::app()->getDocument()->getFullTitle())); ?></title>
		<meta name='description' content='<?php echo esc(Ajde::app()->getDocument()->getDescription()); ?>' />
		<meta name='author' content='<?php echo esc(config("app.author")); ?>' />
		<?php echo Ajde::app()->getDocument()->getMeta(); ?>

		<!-- Mobile presentation meta tags -->
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">
		<meta name="viewport" content="width=device-width">
		<meta http-equiv="cleartype" content="on">

		<!-- Define the root of the site -->
		<base href='<?php echo config("i18n.rootUrl"); ?>' />

		<!-- Make IE6-8 HTML5 compliant, somewhat... -->
		<!--[if lt IE 9]>
		<script src='public/js/lib/html5shiv.js'></script>
		<![endif]-->

		<!-- Favicon and CSS -->
		<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
		<?php echo $this->getDocument()->getHead('css'); ?>

	</head>

	<body>

		<!-- No JavaScript / No cookies warning -->
		<noscript>
			<div class="no-js-cookie-warning">This site works best with JavaScript enabled</div>
		</noscript>
		<script defer='defer'>
			if (navigator.cookieEnabled === false) {
				document.write('<div class="no-js-cookie-warning">This site works best with cookies enabled</div>');
			}
		</script>

        <!-- Admin shortcut -->
        <a class="ajde-shortcut site" href="./" target="site">site</a>

		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container-fluid">
					<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
						  <span class="icon-bar"></span>
					</button>
					<a class="brand" href="admin"><?php echo config("app.title"); ?></a>
					<?php echo $this->includeModule('admin/nav'); ?>
				</div>
			</div>
		</div>

		<div class="container-fluid">

            <div class="row-fluid">
                <div id="no-chrome-warning" class="chrome alert menu-offset">
                    <img src="https://lh3.ggpht.com/7O3H3V0fEBumwJlqDLD03t1fmwl8fH9YoBsPwB2UQ_aiBilM7OAOe2gkFB3wrojJqbM=w50" class="pull-left" alt="Chrome logo" />
                    <p>
                        The website you're managing is optimized for all regular browsers. This administration section however, works best with Google Chrome.<br/>
                        <i class="icon-chevron-right icon-white"></i><a href="http://chrome.google.com">Please  download &amp; install Google Chrome</a>
                    </p>
                </div>
            </div>

            <div id="main">
                <?php echo $this->getDocument()->getBody(); ?>
            </div>

            <div class="clearfix"></div>

            <div class="row-fluid">
                <footer class="menu-offset">
                    <p class="text-center ajde-footer">
                        Powered by <a href="https://github.com/hongaar/ajde"><img src="<?php echo MEDIA_DIR; ?>ajde-small.png" style="height: 15px;" /></a> web administration platform
                    </p>
                </footer>
            </div>

		</div>

		<div id="loading">
			<div>
				<div class="spinner"><strong>loading...</strong><span></span></div>
			</div>
		</div>

		<!-- The scripts -->
		<?php echo $this->getDocument()->getScripts(); ?>

		<!-- updatemybrowser.org widget -->
        <script>
            (function(u) {
                var s = document.createElement('script'); s.async = true; s.src = u;
                var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(s, b);
            })('//updatemybrowser.org/umb.js');
        </script>

	</body>
</html>

<?php if (config("app.debug")) { ?>
<!-- Some debugging info -->
<pre style="position: relative; z-index: 99;"><?php echo config("app.id") . ', ' . config("app.version"); ?> | Cache <?php echo Ajde_Cache::getInstance()->isEnabled() ? 'enabled' : 'disabled' ?> | Last modified on <?php echo date("r", Ajde_Cache::getInstance()->getLastModified()); ?></pre>
<?php } ?>
