<?php 

// Node types
Ajde_Model::register('admin');

$mediaTypes = new MediatypeCollection();
$mediaTypes->orderBy('category');
$mediaTypes->orderBy('sort');

$currentGrouper = '';

?>

<div class="btn-group">
	<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
		type <span class="caret"></span>
	</a>
	<ul class="dropdown-menu pull-right type">
		<?php foreach ($mediaTypes as $mediaType) {  
			/* @var $mediaType MediatypeModel */
			if ($mediaType->get('category') <> $currentGrouper) {
				if (!empty($currentGrouper)) { echo '</ul>'; }
				$currentGrouper = $mediaType->get('category'); ?>
				<li class="with-sub-menu">
					<a href="javascript:void(null);">
						<?php echo ucfirst($currentGrouper); ?> <i class="icon-chevron-right pull-right"></i>
					</a>
					<ul class="dropdown-menu sub-menu">
			<?php } ?>
			<li><a href="javascript:void(null);" data-id="<?php echo $mediaType->getPK(); ?>"><?php echo _e($mediaType->getName()); ?></a></li>
		<?php }
		if ($mediaTypes->count() && !empty($currentGrouper)) { ?>
			</ul>
		</li>
		<?php } ?>
	</ul>
</div>