<?php 
/* @var $field Ajde_Crud_Field */
$field = $this->field;
?>
   
<div class="control-group <?php if ($field->hasHidden() && $field->getHidden() === true) { echo 'hidden'; } ?>">

    <?php if (($field->hasShowLabel() && $field->getShowLabel() !== false) || !$field->hasShowLabel()) { ?>
        <label class='control-label' for='in_<?php echo $field->getName(); ?>' title='<?php echo $field->getLabel(); ?>' class='<?php if ($field->getIsRequired() === true) { echo 'required'; } ?>'>
            <?php echo __($field->getLabel()); ?>    

            <?php if ($field->getIsRequired() === true) :
                echo $field->getHtmlRequired();
            endif; ?>
        </label>

    <?php } ?>

    <div class="controls">
        <?php if ($field->hasHelp()) :
            echo "<span class='help'>" . $field->getHelp() . "</span>";
        endif; ?>
        <?php if ($field->getIsPK() === true) :
            echo $field->getHtmlPK();
        endif; ?>
        <?php echo $field->getInput(); ?>
    </div>
        
</div>