<?php
/* @var $crud Ajde_Crud */
$crud = $this->crud;
$editOptions = $crud->getOptions('edit');

$topToolbarTreshold = 30;

$readOnly = $crud->getOption('edit.readonly', false);
$autosave = $crud->getOption('edit.autosave', true);

// Total fields
$rows = $crud->getOption('edit.layout.rows');

$totalFields = 0;
foreach($rows as $row) {
	$columns = $row['columns'];
	foreach($columns as $column) {
		$blocks = $column['blocks'];
		foreach($blocks as $block) {
			$fieldsToShow = issetor($block['show']);
            $totalFields += count($fieldsToShow);
		}
	}
}

echo $this->ACAjaxForm('_core/crud:commit', $crud->getHash(), 'ACCrud ACCrudEdit form-horizontal' . ($autosave ? ' autosave' : '')); ?>

	<div class='data' data-listaction='<?php echo $crud->getListAction(); ?>'></div>

	<?php if (0 && $totalFields > $topToolbarTreshold) { // disabled, with fixed bottom bar ?>
    <div class="form-actions">

        <?php if ($autosave) { ?>
            <div class="autosave-group">
                <a href="javascript:void(null);" class='autosave btn btn-primary cancel' title='Go back to overview'>back</a>
                <span class="autosave autosave-status"></span>
            </div>
        <?php } ?>
        <div class="regular-group">
            <?php if (!$readOnly) { ?>
                <div class="btn-group">
                    <button type="submit" class="btn btn-success save" title='Save changes and go back to overview'><i class='icon-ok icon-white'></i> save &amp; back</button>
                    <button type="submit" class="btn btn-primary apply" title='Save changes'>save</button>
                </div>
                <a href="javascript:void(null);" class='btn pull-right cancel' title='Go back to overview'>back</a>
            <?php } else { ?>
                <a href="javascript:void(null);" class='btn btn-primary cancel' title='Go back to overview'>back</a>
            <?php } ?>
        </div>

    </div>
	<?php } ?>

    <?php

    $fieldsShown = array();
    foreach($rows as $row) {
        $columns = $row['columns'];
        ?>

        <div class='row-fluid'>

        <?php
        foreach($columns as $key => $column) {

            // Styles
            $span = isset($column['span']) ? $column['span'] : '12';
            ?>

            <div class='column span<?php echo $span; ?>'>

            <?php
            $blocks = $column['blocks'];
            foreach($blocks as $block) {
                $fieldsToShow = issetor($block['show']);
                $className = issetor($block['class']);

                if ($fieldsToShow == '*' || $fieldsShown == array('*')) {
                    $fieldsToShow = $crud->getFieldNames();
                }

                ?>

                <fieldset class='crud <?php echo $className; ?>'>

                    <?php if (isset($block['title'])) { ?>
                        <div class="controls">
                            <legend><?php echo $block['title']; ?></legend>
                        </div>
                    <?php } ?>

                    <?php foreach( (isset($fieldsToShow) ? $fieldsToShow : array()) as $fieldName) {

                        $fieldsShown[] = $fieldName;
                        $field = $crud->getField($fieldName, false);
                        if (!$field) {
                            // Dynamically create a text field and fill with value from Model (if available)
                            $field = $crud->createField($crud->getFieldOptions($fieldName, array(
                                'name' => $fieldName,
                                'type' => 'text',
                                'length' => 255,
                                'default' => '',
                                'label' => ucfirst($fieldName),
                                'isRequired' => false,
                                'isPK' => false,				
                                'isAutoIncrement' => false,
                                'isAutoUpdate' => false,
                                'value' => $crud->getModel()->{"has".ucfirst($fieldName)}() ? $crud->getModel()->{"get".ucfirst($fieldName)}() : false
                            )));
                        }
                        echo $field->getHtml();
                    } ?>
                        
                </fieldset>

                <?php
            } ?>

            </div> <!-- /span -->
            <?php
        } ?>			
        </div> <!-- /row -->
        <?php
    }

    ?>

    <?php
    $model = $crud->getItem();
    if ($model instanceof Ajde_Model_With_Revision || $model instanceof Ajde_Model_With_AclRevision || $model instanceof Ajde_Model_With_AclI18nRevision) {
        /* @var $model Ajde_Model_Revision */
        echo $model->getRevisionsHtml($crud);
    }
    ?>

    <div class='hidden'>
        <?php foreach($crud->getFields() as $field) {
            if (!in_array($field->getName(), $fieldsShown)) {
                /** @var Ajde_Crud_Field $field */
                ?>
                <input type="hidden" name="<?php echo _e($field->getName()); ?>" value="<?php echo _e($field->getValue()); ?>" />
                <?php
//                echo $field->getInput();
            }
        } ?>
    </div>

    <div class="form-actions fixed">

        <?php if ($autosave) { ?>
            <div class="autosave-group">
                <a href="javascript:void(null);" class='autosave btn btn-primary cancel' title='Go back to overview'>back</a>
                <span class="autosave autosave-status"></span>
            </div>
        <?php } ?>
        <div class="regular-group">
            <?php if (!$readOnly) { ?>
                <div class="btn-group">
                    <button type="submit" class="btn btn-success save" title='Save changes and go back to overview'><i class='icon-ok icon-white'></i> save &amp; back</button>
                    <button type="submit" class="btn btn-primary apply" title='Save changes'>save</button>
                </div>
                <a href="javascript:void(null);" class='btn pull-right cancel' title='Go back to overview'>back</a>
            <?php } else { ?>
                <a href="javascript:void(null);" class='btn btn-primary cancel' title='Go back to overview'>back</a>
            <?php } ?>
        </div>

    </div>

</form>