<?php 
/* @var $this Ajde_Template_Parser_Phtml_Helper */
$this->requireJsPublic('core/fineuploader/jquery.fineuploader-3.4.1.js');
$this->requireCssPublic('core/fineuploader/fineuploader-3.4.1.css', Ajde_Document_Format_Html::RESOURCE_POSITION_TOP);
?>

<input type='hidden' name='<?php echo $this->name; ?>' />
<div
	class="ACAjaxUpload <?php echo $this->extraClass; ?>"
	id="<?php echo $this->inputId; ?>"
	data-name="<?php echo $this->name; ?>"  
	data-options="<?php echo $this->optionsId; ?>"
	data-multiple="<?php echo ($this->optionsMultiple ? '1' : '0'); ?>"
></div>