<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$this->requireJsPublic('core/complexify/jquery.complexify.banlist.js');
$this->requireJsPublic('core/complexify/jquery.complexify.min.js');

$this->requireCss('register');

?>

<div class="row-fluid">
	<div class="span8 col-8">
	
		<?php if (!isset($this->user)) { ?>
			
			<h2>Password reset link is incorrect</h2>
			
		<?php } else { ?>
			<?php echo $this->ACAjaxForm('user/reset', 'resetform', 'form-horizontal well'); ?>
				<fieldset>
					<legend><?php echo __('Choose a new password'); ?></legend>
					
					<p>
						Your password, e-mail address and other identifiable information will be encrypted securely.<br/>
						<a href='main/disclaimer.html'>Read more</a>
					</p>
					
					<div class="control-group form-group give-status">			
						<div class="controls col-lg-6">
							<p class="help-block status-text"></p>
						</div>
					</div>
					
					<div class="control-group form-group">
						<label class="control-label col-lg-4" for="in_user"><?php echo __(ucfirst($this->user->usernameField)); ?></label>
						<div class="controls col-lg-6" style="padding-top: 6px;"> <!-- I'm sorry... no excuses -->
							<?php echo _e($this->user->get($this->user->usernameField)); ?>
						</div>
					</div>	
					
					<div class="control-group form-group">
						<label class="control-label col-lg-4" for="in_pass1"><?php echo __(ucfirst($this->user->passwordField)); ?></label>
						<div class="controls col-lg-6">
							<input type="password" name="password" placeholder="****" required id="in_pass1" />
							<div class='complexity'>
								<div class='progressbar'><div class='progress'></div></div>
								<div class='class'></div>
							</div>
						</div>
					</div>
					
					<div class="control-group form-group">
						<label class="control-label col-lg-4" for="in_pass2"><?php echo __('Verify') . ' ' . __($this->user->passwordField); ?></label>
						<div class="controls col-lg-6">
							<input type="password" name="passwordCheck" placeholder="****" required id="in_pass2" />
						</div>
					</div>
					
					<div class="form-actions col-lg-6 col-lg-offset-4 col-offset-4">
						<button class="btn btn-primary" type="submit"><?php echo __('update'); ?></button>
					</div>
				</fieldset>
			</form>
		<?php } ?>
	
	</div><!--/span-->
    <div class="span4 col-4">
	
		<h2>Have an account?</h2>
		<p>
			Click the link below to log on with an existing account:
		</p>
		<p>
			<a class='btn btn-success' href="user/logon"><?php echo __('logon'); ?></a>
		</p>

	</div>
</div>