<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */

$options = new Ajde_Crud_Options();
$options
	->selectFields()
		->selectField('name')
			->setEmphasis(true)
			->up()
		->selectField('required')
			->setType('boolean')
			->up()
		->selectField('maxlength')
			->setType('numeric')
			->setIsRequired(true)
			->up()
		->up()
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->up()
		->setMain('name')
		->setShow(array('name', 'type'))
		->up()
	->selectEdit()
		->setShow()
		->selectLayout()
			->addRow()
				->addColumn()
                    ->setSpan(12)
					->addBlock()
						->setShow(array('name', 'type'))
						->up()
					->addBlock()
						->setTitle('Options')
						->setShow(array('required'))
						->up()
					
	->finished();

/* @var $decorator Ajde_Crud_Cms_MetaDecorator */
$decorator = $this->decorator;
$decorator->setActiveBlock(1);
$decorator->decorateCrudOptions($options);

var_dump($options->_stack['edit']['layout']['rows'][0]['columns'][0]['blocks'][1]['show']);

$crud = $this->ACCrudList('meta', $options);
	
?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/cms:setupmenu'); ?>		
	</div><!--/span-->
	<div class="span10 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>	

		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->