<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */


$options = new Ajde_Crud_Options();
$options
    ->selectFields()
        ->selectField('name')
            ->setEmphasis(true)
            ->up()
        ->selectField('sort')
            ->setType('sort')
            ->up()
        ->selectField('email')
            ->up()
        ->selectField('email_to')
            ->setAdvancedFilter(array(
                new Ajde_Filter_Where('target', Ajde_Filter::FILTER_EQUALS, 'form')
            ))
            ->up()
        ->selectField('meta')
            ->setType('multiple')
            ->setEditRoute('admin/setup:meta.crud')
            ->setShowLabel(false)
            ->setCrossReferenceTable('form_meta')
            ->addTableField('type')
            ->addSortField('sort')
            ->addPrefillField('target', 'form')
            ->setAdvancedFilter(array(
                new Ajde_Filter_Where('target', Ajde_Filter::FILTER_EQUALS, 'form')
            ))
            ->up()
        ->selectField('submit_text')
            ->setLabel('Submit button text')
            ->up()
        ->up()
    ->selectList()
        ->selectButtons()
            ->setNew(true)
            ->setEdit(true)
//			->addItemButton('meta', 'meta')
            ->up()
        ->setMain('name')
        ->setShow(array('name'))
        ->selectView()
            ->setOrderBy('name')
            ->up()
        ->up()
    ->selectEdit()
        ->selectLayout()
            ->addRow()
                ->addColumn()
                    ->setSpan(12)
                    ->addBlock()
                        ->setShow(array('name', 'email', 'email_to', 'submit_text'))
                        ->up()
                    ->addBlock()
                        ->setShow(array('meta'))
                        ->setTitle('Meta fields')
                        ->up()
                    ->up()

    ->finished();

$crud = $this->ACCrudList('form', $options);

?>

<div class="row-fluid">
	<div class="span2 hideInIframe">
		<?php echo $this->includeModule('admin/cms:menu'); ?>
	</div><!--/span-->
	<div class="span10 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>

        <?php if (!Ajde::app()->getRequest()->has('edit') && !Ajde::app()->getRequest()->has('new')) {
            echo $this->includeModule('admin/form:menu');
        } ?>
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->