<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<ul>
	<li><a href='admin/view.html'>Dashboard</a></li> 
	
	<?php if (Ajde_User::getLoggedIn()->usergroup == Ajde_User::USERGROUP_ADMINS) { ?>
		<li>Admin bar</li>	 
		<li><a href='admin/posttype.html'>Posts types</a></li>
		<li><a href='admin/meta.html'>Metadata</a></li>
	<?php } ?>
	
	<?php if (Ajde_User::getLoggedIn()->usergroup > Ajde_User::USERGROUP_USERS) { ?>
		<li>Editor bar</li>
		<li><a href='post/edit.html'>Posts</a></li> 
		<li><a href='tag/edit.html'>Tags</a></li> 
		<li><a href='media/edit.html'>Media</a></li> 
	<?php } ?>
</ul>