<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<ul>
	<li><a href='admin/dashboard.html'>Dashboard</a></li> 
	
	<li>Admin bar</li>	 
	<li><a href='post/edit.html'>All posts</a></li>
	<li><a href='post/type.html'>Posts types</a></li>
	<li><a href='meta/edit.html'>Metadata</a></li>
	
	<li>Editor bar</li>
	<li><a href='post/edit.html'>Posts</a></li> 
	<li><a href='tag/edit.html'>Tags</a></li> 
</ul>