<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ ?>

<h2>
	<a href='admin'>&lt;</a>
	Static pages
</h2>

<?php

$options = new Ajde_Crud_Options();
$options	
	->selectFields()
		->selectField('name')
			->setEmphasis(true)
			->up()
		->selectField('image')
			->setType('file')
			->setSaveDir('public/images/uploads/')
			->setExtensions(array('png', 'jpg'))
			->setMultiple(false)
			->setThumbDim(266, 100)
			->up()
		->selectField('published')
			->setType('boolean')
			->setHelp('Item is visible or not')
			->up()
		->selectField('sort')
			->setType('sort')
			->up()
		->selectField('url')
			->setIsReadonly(true)
			->setLabel('URL')
			->up()
		->selectField('media')
			->setType('multiple')
			->setEditRoute('admin/media.crud')
			->addTableFileField('filename', 'public/images/uploads/')
			->setShowLabel(false)
			->up()
		->selectField('tag')
			->setType('multiple')
			->setEditRoute('admin/tag.crud')
			->setThumbDim(30, 30)
			->setShowLabel(false)
			->setCrossReferenceTable('portfolio_tag')
			->up()
		->selectField('added')
			->setIsReadonly(true)
			->up()
		->up()			
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->setCustom('view', 'View', 'view')
			->up()
		->setMain('name')
		->setShow(array('image', 'name', 'updated'))
		->setThumbDim(50, 50)
		->selectView()
			->addFilter('type', 'static')
			->setOrderBy('sort')
			->up()
		->up()
	->selectEdit()
		->setShow()
		->selectLayout()
			->addRow()
				->addColumn()
					->addBlock()
						->setShow(array('name', 'subtitle', 'content', 'sidebar'))
						->up()					
					->up()
				->addColumn()
					->setWidth(350)
					->setAlign('right')					
					->addBlock()
						->setTitle('Featured image')
						->setClass('sidebar')
						->setShow(array('image'))
						->up()					
					->addBlock()
						->setTitle('Metadata')
						->setClass('sidebar')
						->setShow(array('added', 'updated', 'url', 'user'))
						->up()
		
	->finished();

$crud = $this->ACCrudList('portfolio', $options);
$crud->setSessionName('statics');

if (Ajde::app()->getRequest()->has('new')) {
	$user = UserModel::getLoggedIn();
	$crud->setOption('fields.user.value', $user->getPK());		
}

echo $crud->output();

?>