<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="row-fluid">
	<div class="span2">
	</div><!--/span-->
	<div class="span8">
		<div class="hero-unit">
			<h1><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></h1>
			<p>Yay, you reached the dashboard!</p>
			<p><a href="admin/cms:nodes" class="btn btn-primary btn-large">Add content &raquo;</a></p>
		</div>
		<div class="row-fluid">
			<div class="span4">
				<h2>Nodes</h2>
				<p>Can be anything which is a single page on the website</p>
				<p><a class="btn" href="admin/node:view">Manage nodes &raquo;</a></p>
			</div><!--/span-->
			<div class="span4">
				<h2>Media</h2>
				<p>Files and embedded media such as video and audio</p>
				<p><a class="btn" href="admin/media:view">View all media &raquo;</a></p>
			</div><!--/span-->
			<div class="span4">
				<h2>Menus</h2>
				<p>Manage what nodes users can access from the menus</p>
				<p><a class="btn" href="admin/menus:view">Menu overview &raquo;</a></p>
			</div><!--/span-->
		</div><!--/row-->
	</div><!--/span-->
</div><!--/row-->