<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */
?>

<div class="row-fluid">
	<div class="span2">
	</div><!--/span-->
	<div class="span8">
		<div class="hero-unit">
			<h1><?php echo _e(Ajde::app()->getDocument()->getTitle()); ?></h1>
			<p>Yay, you reached the dashboard!</p>
			<p><a href="admin/cms:nodes" class="btn btn-primary btn-large">Get started with nodes &raquo;</a></p>
		</div>
		<div class="row-fluid">
			<div class="span4">
				<h2>Nodes</h2>
				<p>What are nodes?</p>
				<p><a class="btn" href="#">Manage nodes &raquo;</a></p>
			</div><!--/span-->
			<div class="span4">
				<h2>Media</h2>
				<p>What are media?</p>
				<p><a class="btn" href="#">Add new media files &raquo;</a></p>
			</div><!--/span-->
			<div class="span4">
				<h2>Menus</h2>
				<p>What are menus?</p>
				<p><a class="btn" href="#">Menu overview &raquo;</a></p>
			</div><!--/span-->
		</div><!--/row-->
	</div><!--/span-->
</div><!--/row-->