<?php
/* @var $this Ajde_Template_Parser_Phtml_Helper */ 

$updater = $this->updater;
/* @var $updater Ajde_Core_Updater */ 
?>

<div class="row-fluid">
	<div class="span12">		
		<div class="page-header">
			<h1>
				<?php echo _e(Ajde::app()->getDocument()->getTitle()); ?>
			</h1>
		</div>			
	</div>
</div>

<div class="row-fluid">		
			
	<?php if ($updater->isUpdateable()) { ?>
	
		<div class="span4">
		
			<h2>Update available!</h2>
		
			<p>
				<span class='label label-warning'>Current: <?php echo $updater->getCurrentVersion(); ?></span>
				New version available: <?php echo $updater->getAvailableVersion(); ?>
			</p>
			
			<?php echo $this->ACAjaxForm('admin/system:update', 'systemUpdateForm'); ?>
				<input type='hidden' name='step' value='start' />
				<button type="submit" class="btn btn-primary btn-large">Update now</button>
			</form>
			
			<div id="status" class="well">
				<p>
					Starting update...
				</p>
				<div class="progress progress-striped active">
					<div class="bar" style="width: 0%;"></div>
				</div>
			</div>
			
		</div>
		
		<div class="span8">
		
			<h2>Changelog:</h2>
			
			<?php echo $this->ACMarkdown(array('text' => $updater->getChangelog())); ?>
		
		</div>
		
	<?php } else { ?>
	
		<div class="span12">
		
			<h2>You are up to date!</h2>
		
			<p>
				<span class='label label-success'>Current: <?php echo $updater->getCurrentVersion(); ?></span>
				Current version is up to date.				
			</p>
			
		</div>
	
	<?php } ?>

</div><!--/row-->