<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ ?>

<h2>Edit</h2>

<?php	

$options = new Ajde_Crud_Options();
$options	
	->selectFields()
		->selectField('name')
			->setEmphasis(true)
			->up()
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
					->addBlock()
						->setShow(array('name', 'place', 'country'))				
		
	->finished();

$crud = $this->ACCrudList('distributor', $options);

echo $crud->output();