<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ ?>

<h2>Edit</h2>

<?php	

$options = new Ajde_Crud_Options();
$options	
	->selectFields()
		->selectField('title')
			->setEmphasis(true)
			->up()
		->selectField('image')
			->setType('file')
			->setSaveDir('public/images/uploads/')
			->setExtensions(array('png', 'jpg', 'pdf', 'docx'))
			->setMultiple(false)
			->setLabel('Plaatje')
			->setLength(255)
			->setIsRequired(false)
			->setDefault('')
			->setIsAutoIncrement(false)
			->setHelp('Please select an image, or drag and drop here, this is a long helptext spanning several lines. So you can see the transition effect. Oh yeah')			
			->setThumbDim(266, 100)
			->up()
		->selectField('published')
			->setType('boolean')
			->setHelp('Post is visible or not')
			->up()
		->selectField('sort')
			->setType('sort')
			->up()
		->selectField('unitprice')
			->setHelp('Sets the unit price, oh yeah..')
			->up()
		->up()			
	->selectList()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->setCustom('view', 'View article', 'view')
			->up()
		->setMain('title')
		->setShow(array('title', 'updated', 'image', 'published', 'type', 'sort'))
		->setThumbDim(30, 30)
		->selectView()
			->setOrderBy('sort')			
			->up()
		->up()
	->selectEdit()
		->setShow()
		->selectLayout()
			->addRow()
				->addColumn()
					->addBlock()
						->setShow(array('title', 'content'))
						->up()
					->addBlock()
						->setTitle('Pricing')
						->setClass('table')
						->setShow(array('unitprice', 'vat'))
						->up()
					->up()
				->addColumn()
					->setWidth(300)
					->setAlign('right')
					->addBlock()
						->setTitle('Metadata')
						->setClass('sidebar')
						->setShow(array('updated', 'published', 'optional_field', 'user', 'sort'))
						->up()
					->addBlock()
						->setTitle('Media')
						->setClass('sidebar')
						->setShow(array('image', 'type'))
		
	->finished();

$crud = $this->ACCrudList('sample', $options);

if (Ajde::app()->getRequest()->has('new')) {
	$user = UserModel::getLoggedIn();
	$crud->setOption('fields.user.value', $user->getPK());		
}

echo $crud->output();