<?php 
/* @var $field Ajde_Crud_Field */
$field = $this->field;
?>
   
<div
	class="control-group
	<?php if (
			($field->hasHidden() && $field->getHidden() === true)
//			|| $field->hasShowOnlyWhen()
			) { echo 'hidden'; } ?>
	<?php if ($field->hasShowOnlyWhen()) {
		echo 'dynamic" ';
		$showOnlyWhens = $field->getShowOnlyWhen();
		foreach($showOnlyWhens as $key => $showOnlyWhen) {
			echo 'data-show-' . $key . '="|' . implode('|', $showOnlyWhen) . '|"';
		}
	} else {
		echo '"';
	} ?>
>

    <?php if (($field->hasShowLabel() && $field->getShowLabel() !== false) || !$field->hasShowLabel()) { ?>
        <label class='control-label' for='in_<?php echo $field->getName(); ?>' title='<?php echo $field->getLabel(); ?>' class='<?php if ($field->getIsRequired() === true) { echo 'required'; } ?>'>
            <?php echo __($field->getLabel()); ?>    

            <?php if ($field->getIsRequired() === true) :
                echo $field->getHtmlRequired();
            endif; ?>
        </label>

    <?php } ?>

    <div class="controls">        
        <?php if ($field->hasIsPK() && $field->getIsPK() === true) :
            echo $field->getHtmlPK();
        endif; ?>
        <?php echo $field->getInput(); ?>
        <?php if ($field->hasHelp()) :
            echo "<span class='help-inline'>" . $field->getHelp() . "</span>";
        endif; ?>
    </div>
        
</div>