<?php /* @var $this Ajde_Template_Parser_Phtml_Helper */ 

/* @var $options Ajde_Crud_Options */
$options = $this->options;

if (UserModel::isAdmin()) {
	$showUsers = array('users');
} else {
	$showUsers = array();
}

$options
	->selectFields()
		->selectField('childrencount')
			->setLabel('Projects')
			->setFunction('displayChildrenCount')
			->up()
		->selectField('users')
			->setLabel('User access')
			->setType('multiple')
			->setEditRoute('admin/user:view.crud')
			->setListRoute('admin/user:view.crud')
			->setSimpleSelector(true)
			->setModelName('user')
			->setCrossReferenceTable('user_node')
			->up()
		->up()			
	->selectList()
		->setShow(array('title', 'childrencount'))
		->selectView()
			->setOrderBy('title')
			->up()
		->selectButtons()
			->setNew(true)
			->setEdit(true)
			->setDelete(false)
			->setSelect(false)
			->addItemButton('projects', 'projects')
			->up()
		->up()
	->selectEdit()
		->selectLayout()
			->addRow()
				->addColumn()
					->setSpan(8)
					->addBlock()
						->setShow($showUsers)
->finished();

$crud = $this->ACCrudList('node', $options);
$crud->setSessionName('client');
$crud->setNewAction('client?view[filter][nodetype]=' . NodeModel::NODETYPE_CLIENT);

$filterGroup = new Ajde_Filter_WhereGroup();
$filters = array(
	NodeModel::NODETYPE_CLIENT
);
foreach ($filters as $filter) {
	$filterGroup->addFilter(new Ajde_Filter_Where('nodetype', Ajde_Filter_Where::FILTER_EQUALS, $filter, Ajde_Query::OP_OR));
}
$crud->getCollection()->addFilter($filterGroup);

if (!Ajde::app()->getRequest()->has('edit') && !Ajde::app()->getRequest()->has('new')) {
	// LIST 
	
	// remove mainfilter
	$crudView = $crud->getCollectionView();
	$crudView->setFilter(array());
	
	// add node type
	$crud->getCollection()->joinNodetype();
	$crud->getCollection()->getQuery()->addSelect('nodetype.name AS nodetype_name');
	
	// add childrencount
	$crud->getCollection()->getQuery()->addSelect('NULL AS childrencount');
}

?>

<div class="row-fluid">
	<div class="span12 expandInIframe">
		
		<div class="page-header">
			<h1>
				<?php echo Ajde::app()->getDocument()->getTitle(); ?>
			</h1>
		</div>		
		
		<?php echo $crud->output(); ?>
		
	</div><!--/span-->
</div><!--/row-->