<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
<style>
	body {
		padding: 20px;
		text-align: center;
	}
</style>
<h1><?php echo Config::get('sitename'); ?></h1>
<h3>Cookies are disabled in your browser</h3>
<h4>
	Please <a target="_blank" href="http://www.wikihow.com/Enable-Cookies-in-Your-Internet-Web-Browser">enable cookies</a> to view this website
</h4>
<p>
	&nbsp;<br/>
	<a class="btn btn-primary btn-large" href="<?php echo Config::get('site_root'); echo $this->returnto; ?>">
		<i class="icon-refresh icon-white"></i> Try again
	</a>
</p>
<script>
if (typeof history.replaceState !== 'undefined') {
	history.replaceState('', 'root', '<?php echo Config::get('site_root'); echo $this->returnto; ?>');
}
</script>